import { createHash } from "node:crypto";
import { createServer } from "node:http";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { spawn } from "node:child_process";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const WORKER_VERSION = "0.1.0";
const PRUSA_PINNED = "2.8.1";
const APP_BASE_URL = process.env.APP_BASE_URL ?? "http://127.0.0.1:3000";
const SECRET = process.env.SLICER_WORKER_SECRET ?? "";
const WORKER_ID = process.env.SLICER_WORKER_ID ?? `slicer-${process.pid}`;
const BIN =
  process.env.PRUSA_SLICER_BIN ??
  "/opt/prusa-slicer/usr/bin/prusa-slicer";
const PROFILE_ROOT =
  process.env.SLICER_PROFILE_ROOT ?? path.join(__dirname, "..", "profiles");
const JOB_ROOT = process.env.SLICER_JOB_ROOT ?? "/tmp/slicer-jobs";
const SLICE_TIMEOUT_MS = Number(process.env.SLICER_TIMEOUT_MS ?? 8 * 60 * 1000);
const ALLOWED_QUALITY = new Set(["ekonomik", "standart", "detayli"]);
const ALLOWED_INFILL = new Set([10, 15, 20, 30, 50, 100]);
const ALLOWED_SUPPORTS = new Set(["auto", "on", "off"]);

const TIME_RE =
  /estimated printing time \(normal mode\)\s*=\s*(?:(\d+)d\s*)?(?:(\d+)h\s*)?(?:(\d+)m\s*)?(?:(\d+)s)?/i;
const FILAMENT_MM_RE = /filament used \[mm\]\s*=\s*([0-9.]+)/i;
const FILAMENT_G_RE = /filament used \[g\]\s*=\s*([0-9.]+)/i;
const LAYERS_RE = /total layers count\s*=\s*(\d+)/i;
const ENGINE_RE = /generated by\s+(.+?)\s+on /i;

function headers() {
  return {
    Authorization: `Bearer ${SECRET}`,
    "Content-Type": "application/json",
    "x-slicer-worker-id": WORKER_ID,
    "x-slicer-worker-version": WORKER_VERSION,
    "x-prusa-slicer-version": PRUSA_PINNED,
  };
}

function parseGcode(text) {
  const mm = text.match(FILAMENT_MM_RE);
  const grams = text.match(FILAMENT_G_RE);
  const time = text.match(TIME_RE);
  if (!mm || !grams || !time) {
    throw new Error("G-code metadata eksik.");
  }
  const duration =
    Number(time[1] ?? 0) * 86400 +
    Number(time[2] ?? 0) * 3600 +
    Number(time[3] ?? 0) * 60 +
    Number(time[4] ?? 0);
  const layers = text.match(LAYERS_RE);
  const layerChanges = text.match(/;LAYER_CHANGE\b/g);
  const engine = text.match(ENGINE_RE);
  return {
    filamentLengthMm: Number(mm[1]),
    filamentWeightGrams: Number(grams[1]),
    estimatedDurationSeconds: duration,
    layerCount: layers
      ? Number(layers[1])
      : layerChanges
        ? layerChanges.length
        : null,
    engineVersion: engine?.[1]?.trim() ?? `PrusaSlicer ${PRUSA_PINNED}`,
  };
}

async function profileChecksum() {
  const files = [
    "printer/bambu-a1-dev.ini",
    "filament/pla.ini",
    "print/ekonomik.ini",
    "print/standart.ini",
    "print/detayli.ini",
  ];
  const hash = createHash("sha256");
  for (const relative of files) {
    hash.update(await readFile(path.join(PROFILE_ROOT, relative)));
  }
  return hash.digest("hex");
}

function runSlicer(args, cwd, timeoutMs) {
  return new Promise((resolve, reject) => {
    const child = spawn(BIN, args, {
      cwd,
      env: { ...process.env, HOME: cwd, TMPDIR: cwd },
      stdio: ["ignore", "pipe", "pipe"],
    });
    let stdout = "";
    let stderr = "";
    child.stdout.on("data", (chunk) => {
      stdout += chunk.toString("utf8").slice(0, 4000);
    });
    child.stderr.on("data", (chunk) => {
      stderr += chunk.toString("utf8").slice(0, 4000);
    });
    const timer = setTimeout(() => {
      child.kill("SIGKILL");
      reject(new Error("PrusaSlicer zaman aşımı."));
    }, timeoutMs);
    child.on("error", (error) => {
      clearTimeout(timer);
      reject(error);
    });
    child.on("exit", (code) => {
      clearTimeout(timer);
      if (code !== 0) {
        reject(new Error(`PrusaSlicer çıktı kodu ${code}. ${stderr.slice(0, 300)}`));
        return;
      }
      resolve({ stdout, stderr });
    });
  });
}

function sanitizeLog(text) {
  return text
    .replace(SECRET, "[redacted]")
    .replace(/https?:\/\/[^\s]+/g, "[url]")
    .slice(0, 2000);
}

async function processJob(job) {
  const dir = path.join(JOB_ROOT, job.id);
  await mkdir(dir, { recursive: true });
  try {
    const config = job.configuration;
    if (config.materialId !== "pla") {
      throw new Error("Yalnız PLA otomatik dilimlenir.");
    }
    if (!ALLOWED_QUALITY.has(config.qualityId)) {
      throw new Error("Kalite profili geçersiz.");
    }
    if (!ALLOWED_INFILL.has(config.infillPercent)) {
      throw new Error("Dolgu değeri izin listesinde değil.");
    }
    if (!ALLOWED_SUPPORTS.has(config.supports)) {
      throw new Error("Destek ayarı geçersiz.");
    }

    const downloadUrl = new URL(job.downloadPath, APP_BASE_URL);
    const response = await fetch(downloadUrl, { headers: headers() });
    if (!response.ok) {
      throw new Error(`Dosya indirilemedi (${response.status}).`);
    }
    const bytes = Buffer.from(await response.arrayBuffer());
    const inputPath = path.join(dir, `model.${job.format}`);
    const outputPath = path.join(dir, "out.gcode");
    const overridePath = path.join(dir, "override.ini");
    await writeFile(inputPath, bytes);

    const support =
      config.supports === "off" ? "0" : "1";
    const auto = config.supports === "auto" ? "1" : "0";
    await writeFile(
      overridePath,
      [
        `fill_density = ${config.infillPercent}%`,
        `support_material = ${support}`,
        `support_material_auto = ${auto}`,
        `scale = ${config.scalePercent}%`,
      ].join("\n"),
      "utf8",
    );

    const rotateX = job.analysis?.flags?.includes("does_not_fit") ? 90 : 0;
    const args = [
      "--export-gcode",
      "--output",
      outputPath,
      "--load",
      path.join(PROFILE_ROOT, "printer/bambu-a1-dev.ini"),
      "--load",
      path.join(PROFILE_ROOT, "filament/pla.ini"),
      "--load",
      path.join(PROFILE_ROOT, `print/${config.qualityId}.ini`),
      "--load",
      overridePath,
      "--center",
      "128,128",
    ];
    if (rotateX) {
      args.push("--rotate-x", String(rotateX));
    }
    args.push(inputPath);

    const slicer = await runSlicer(args, dir, SLICE_TIMEOUT_MS);
    const gcode = await readFile(outputPath, "utf8");
    const parsed = parseGcode(gcode);
    const checksum = await profileChecksum();
    const dims = job.analysis?.dimensionsMm ?? { x: 0, y: 0, z: 0 };

    await fetch(new URL(`/api/internal/slicer/jobs/${job.id}/result`, APP_BASE_URL), {
      method: "POST",
      headers: headers(),
      body: JSON.stringify({
        ok: true,
        logsSanitized: sanitizeLog(`${slicer.stdout}\n${slicer.stderr}`),
        flags: job.analysis?.flags ?? [],
        metrics: {
          dimensionsMm: dims,
          filamentLengthMm: parsed.filamentLengthMm,
          filamentWeightGrams: parsed.filamentWeightGrams,
          estimatedDurationSeconds: parsed.estimatedDurationSeconds,
          layerCount: parsed.layerCount,
          supportUsed: config.supports !== "off",
          materialId: "pla",
          qualityId: config.qualityId,
          quantity: config.quantity,
          orientation: { rotateX, rotateY: 0, rotateZ: 0 },
          engine: { name: "PrusaSlicer", version: parsed.engineVersion },
          profileChecksum: checksum,
          warnings: [],
        },
      }),
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Bilinmeyen işçi hatası.";
    await fetch(new URL(`/api/internal/slicer/jobs/${job.id}/result`, APP_BASE_URL), {
      method: "POST",
      headers: headers(),
      body: JSON.stringify({
        ok: false,
        errorCode: message.includes("zaman aşımı") ? "timeout" : "slicer_failure",
        errorMessage: message.slice(0, 400),
        logsSanitized: sanitizeLog(message),
      }),
    });
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
}

async function tick() {
  if (!SECRET) {
    console.error("SLICER_WORKER_SECRET missing");
    return;
  }
  const response = await fetch(new URL("/api/internal/slicer/claim", APP_BASE_URL), {
    method: "POST",
    headers: headers(),
  });
  if (!response.ok) {
    return;
  }
  const payload = await response.json();
  if (!payload?.job) {
    return;
  }
  await processJob(payload.job);
}

function startHealthServer() {
  const port = Number(process.env.PORT ?? 8788);
  const server = createServer((req, res) => {
    if (req.url === "/health") {
      res.writeHead(200, { "Content-Type": "application/json" });
      res.end(
        JSON.stringify({
          ok: true,
          workerVersion: WORKER_VERSION,
          prusaSlicerPinned: PRUSA_PINNED,
          authenticated: Boolean(SECRET),
        }),
      );
      return;
    }
    res.writeHead(404);
    res.end();
  });
  server.listen(port, "0.0.0.0");
  return server;
}

const server = startHealthServer();
let pollInterval = null;
if (!SECRET) {
  console.error("SLICER_WORKER_SECRET missing; polling disabled");
} else {
  console.log(`slicer-worker ${WORKER_VERSION} polling`);
  pollInterval = setInterval(() => {
    tick().catch((error) =>
      console.error("tick failed", error instanceof Error ? error.message : error),
    );
  }, 2500);
  tick().catch(() => undefined);
}

function shutdown(signal) {
  console.log(`slicer-worker shutting down (${signal})`);
  if (pollInterval) {
    clearInterval(pollInterval);
  }
  server.close(() => process.exit(0));
  setTimeout(() => process.exit(0), 5000).unref();
}

process.on("SIGTERM", () => shutdown("SIGTERM"));
process.on("SIGINT", () => shutdown("SIGINT"));
