/** Shared PrusaSlicer G-code metric parser. Must stay aligned with src/domain/manufacturing/gcode.ts */

export const GCODE_PARSER_VERSION = "bc-gcode-support-v1";

const TIME_RE =
  /estimated printing time \(normal mode\)\s*=\s*(?:(\d+)d\s*)?(?:(\d+)h\s*)?(?:(\d+)m\s*)?(?:(\d+)s)?/i;
const FILAMENT_MM_RE = /filament used \[mm\]\s*=\s*([0-9.]+)/i;
const FILAMENT_G_RE = /filament used \[g\]\s*=\s*([0-9.]+)/i;
const LAYERS_RE = /total layers count\s*=\s*(\d+)/i;
const ENGINE_RE = /generated by\s+(.+?)\s+on /i;
const TYPE_RE = /^;TYPE:(.+)$/i;
const LAYER_CHANGE_RE = /^;LAYER_CHANGE\b/;
const EXTRUDE_RE = /(?:^|\s)E(-?\d+(?:\.\d+)?)(?:\s|$)/i;

function isSupportToolpathType(type) {
  const normalized = type.trim().toLowerCase();
  return (
    normalized === "support" ||
    normalized === "support material" ||
    normalized === "support material interface" ||
    normalized.startsWith("support material")
  );
}

function parseDurationSeconds(text) {
  const match = text.match(TIME_RE);
  if (!match) {
    throw new Error("G-code içinde tahmini süre yok.");
  }
  const duration =
    Number(match[1] ?? 0) * 86400 +
    Number(match[2] ?? 0) * 3600 +
    Number(match[3] ?? 0) * 60 +
    Number(match[4] ?? 0);
  if (!Number.isFinite(duration) || duration <= 0) {
    throw new Error("Tahmini süre geçersiz.");
  }
  return duration;
}

function parseSupportToolpaths(gcode) {
  let currentType = "";
  let currentLayer = 0;
  let relativeE = true;
  let lastAbsE = 0;
  let supportMaterialMm = 0;
  const supportLayers = new Set();

  for (const raw of gcode.split(/\r?\n/)) {
    const line = raw.trim();
    if (LAYER_CHANGE_RE.test(line)) {
      currentLayer += 1;
      continue;
    }
    const typeMatch = line.match(TYPE_RE);
    if (typeMatch) {
      currentType = typeMatch[1].trim();
      continue;
    }
    if (/^M83\b/i.test(line)) {
      relativeE = true;
      continue;
    }
    if (/^M82\b/i.test(line)) {
      relativeE = false;
      continue;
    }
    if (!/^G[01]\b/i.test(line)) {
      continue;
    }
    const eMatch = line.match(EXTRUDE_RE);
    if (!eMatch) {
      continue;
    }
    const eValue = Number(eMatch[1]);
    if (!Number.isFinite(eValue)) {
      continue;
    }
    const delta = relativeE ? eValue : eValue - lastAbsE;
    lastAbsE = relativeE ? lastAbsE : eValue;
    if (delta > 0 && isSupportToolpathType(currentType)) {
      supportMaterialMm += delta;
      if (currentLayer > 0) {
        supportLayers.add(currentLayer);
      }
    }
  }

  return {
    supportMaterialMm,
    supportLayerCount: supportLayers.size,
    supportGenerated: supportMaterialMm > 0,
  };
}

export function parseGcode(text) {
  if (!text.includes(";")) {
    throw new Error("G-code metadata yorumları yok.");
  }
  const mm = text.match(FILAMENT_MM_RE);
  const grams = text.match(FILAMENT_G_RE);
  if (!mm || !grams) {
    throw new Error("G-code filament metadata'sı yok.");
  }
  const filamentLengthMm = Number(mm[1]);
  const filamentWeightGrams = Number(grams[1]);
  if (!(filamentLengthMm > 0) || !(filamentWeightGrams > 0)) {
    throw new Error("Filament miktarı geçersiz.");
  }
  const layers = text.match(LAYERS_RE);
  const layerChanges = text.match(/;LAYER_CHANGE\b/g);
  const engine = text.match(ENGINE_RE);
  const support = parseSupportToolpaths(text);
  const supportMaterialGrams =
    filamentLengthMm > 0
      ? (filamentWeightGrams * support.supportMaterialMm) / filamentLengthMm
      : 0;
  return {
    filamentLengthMm,
    filamentWeightGrams,
    estimatedDurationSeconds: parseDurationSeconds(text),
    layerCount: layers
      ? Number(layers[1])
      : layerChanges
        ? layerChanges.length
        : null,
    engineVersion: engine?.[1]?.trim() ?? null,
    gcodeParserVersion: GCODE_PARSER_VERSION,
    supportGenerated: support.supportGenerated,
    supportMaterialMm: support.supportMaterialMm,
    supportMaterialGrams,
    supportLayerCount: support.supportLayerCount,
    supportUsed: support.supportGenerated,
  };
}
