import { describe, expect, it } from "vitest";

import { actualSupportGenerated, parsePrusaGcode, GCODE_PARSER_VERSION } from "./gcode";

const sample = `
; generated by PrusaSlicer 2.8.1+linux on 2026-08-18 at 12:00:00 UTC
; estimated printing time (normal mode) = 12m 8s
; filament used [mm] = 412.33
; filament used [g] = 2.41
; total layers count = 71
G1 X0
`;

describe("PrusaSlicer G-code metadata", () => {
  it("parses filament, duration and layers", () => {
    const parsed = parsePrusaGcode(sample);
    expect(parsed.filamentWeightGrams).toBeCloseTo(2.41);
    expect(parsed.filamentLengthMm).toBeCloseTo(412.33);
    expect(parsed.estimatedDurationSeconds).toBe(12 * 60 + 8);
    expect(parsed.layerCount).toBe(71);
    expect(parsed.engineVersion).toContain("PrusaSlicer 2.8.1");
    expect(parsed.supportGenerated).toBe(false);
    expect(parsed.supportUsed).toBe(false);
    expect(parsed.gcodeParserVersion).toBe(GCODE_PARSER_VERSION);
  });

  it("counts LAYER_CHANGE when total layers count is absent", () => {
    const gcode = `
; generated by PrusaSlicer 2.8.1+linux-x64-GTK3 on 2026-08-18 at 12:00:00 UTC
; estimated printing time (normal mode) = 19m 53s
; filament used [mm] = 1543.70
; filament used [g] = 4.60
;LAYER_CHANGE
;Z:0.2
;LAYER_CHANGE
;Z:0.4
G1 X0
`;
    expect(parsePrusaGcode(gcode).layerCount).toBe(2);
  });

  it("rejects G-code without slicer comments", () => {
    expect(() => parsePrusaGcode("G1 X10\n")).toThrow(/metadata/);
  });

  it("rejects zero or non-finite filament values", () => {
    const missing = `
; generated by PrusaSlicer 2.8.1+linux on 2026-08-18 at 12:00:00 UTC
; estimated printing time (normal mode) = 1m 0s
; filament used [mm] = 12
`;
    expect(() => parsePrusaGcode(missing)).toThrow(/filament metadata|Filament|geçersiz/i);
    const zero = `
; generated by PrusaSlicer 2.8.1+linux on 2026-08-18 at 12:00:00 UTC
; estimated printing time (normal mode) = 1m 0s
; filament used [mm] = 0
; filament used [g] = 0
`;
    expect(() => parsePrusaGcode(zero)).toThrow(/Filament|geçersiz/i);
  });

  it("does not treat support_material config dump as generated supports", () => {
    const gcode = `
; generated by PrusaSlicer 2.8.1+linux-x64-GTK3 on 2026-08-18 at 12:00:00 UTC
; estimated printing time (normal mode) = 19m 53s
; filament used [mm] = 1543.70
; filament used [g] = 4.60
; total layers count = 100
M83 ; use relative distances for extrusion
;LAYER_CHANGE
;TYPE:Perimeter
G1 X10 Y10 E1.5
;TYPE:Internal infill
G1 X11 Y11 E2.0
; support_material = 1
; support_material_auto = 1
; support_material_interface_layers = 3
`;
    const parsed = parsePrusaGcode(gcode);
    expect(parsed.supportGenerated).toBe(false);
    expect(parsed.supportUsed).toBe(false);
    expect(parsed.supportMaterialMm).toBe(0);
    expect(parsed.supportLayerCount).toBe(0);
  });

  it("detects actual support material and interface toolpaths", () => {
    const gcode = `
; generated by PrusaSlicer 2.8.1+linux-x64-GTK3 on 2026-08-18 at 12:00:00 UTC
; estimated printing time (normal mode) = 25m 10s
; filament used [mm] = 2000
; filament used [g] = 6
; total layers count = 40
M83
;LAYER_CHANGE
;TYPE:Support material
G1 X10 Y10 E10
G1 X12 Y12 E5
;TYPE:Support material interface
G1 X13 Y13 E2.5
;LAYER_CHANGE
;TYPE:Perimeter
G1 X20 Y20 E8
;TYPE:Support material
G1 X21 Y21 E4
`;
    const parsed = parsePrusaGcode(gcode);
    expect(parsed.supportGenerated).toBe(true);
    expect(parsed.supportUsed).toBe(true);
    expect(parsed.supportMaterialMm).toBeCloseTo(21.5);
    expect(parsed.supportLayerCount).toBe(2);
    expect(parsed.supportMaterialGrams).toBeCloseTo((6 * 21.5) / 2000);
  });

  it("ignores a supportUsed config flag when no support toolpaths exist", () => {
    expect(actualSupportGenerated({ supportUsed: true })).toBe(false);
    expect(actualSupportGenerated({ supportGenerated: true })).toBe(true);
    expect(actualSupportGenerated({ supportMaterialMm: 12.5 })).toBe(true);
  });
});
