import { describe, expect, it } from "vitest";

import { parsePrusaGcode } from "./gcode";

const sample = `
; generated by PrusaSlicer 2.8.1+linux on 2026-08-18 at 12:00:00 UTC
; estimated printing time (normal mode) = 12m 8s
; filament used [mm] = 412.33
; filament used [g] = 2.41
; total layers count = 71
G1 X0
`;

describe("PrusaSlicer G-code metadata", () => {
  it("parses filament, duration and layers", () => {
    const parsed = parsePrusaGcode(sample);
    expect(parsed.filamentWeightGrams).toBeCloseTo(2.41);
    expect(parsed.filamentLengthMm).toBeCloseTo(412.33);
    expect(parsed.estimatedDurationSeconds).toBe(12 * 60 + 8);
    expect(parsed.layerCount).toBe(71);
    expect(parsed.engineVersion).toContain("PrusaSlicer 2.8.1");
  });

  it("counts LAYER_CHANGE when total layers count is absent", () => {
    const gcode = `
; generated by PrusaSlicer 2.8.1+linux-x64-GTK3 on 2026-08-18 at 12:00:00 UTC
; estimated printing time (normal mode) = 19m 53s
; filament used [mm] = 1543.70
; filament used [g] = 4.60
;LAYER_CHANGE
;Z:0.2
;LAYER_CHANGE
;Z:0.4
G1 X0
`;
    expect(parsePrusaGcode(gcode).layerCount).toBe(2);
  });

  it("rejects G-code without slicer comments", () => {
    expect(() => parsePrusaGcode("G1 X10\n")).toThrow(/metadata/);
  });

  it("rejects zero or non-finite filament values", () => {
    const missing = `
; generated by PrusaSlicer 2.8.1+linux on 2026-08-18 at 12:00:00 UTC
; estimated printing time (normal mode) = 1m 0s
; filament used [mm] = 12
`;
    expect(() => parsePrusaGcode(missing)).toThrow(/filament metadata|Filament|geçersiz/i);
    const zero = `
; generated by PrusaSlicer 2.8.1+linux on 2026-08-18 at 12:00:00 UTC
; estimated printing time (normal mode) = 1m 0s
; filament used [mm] = 0
; filament used [g] = 0
`;
    expect(() => parsePrusaGcode(zero)).toThrow(/Filament|geçersiz/i);
  });
});
