import type { SlicingMetrics } from "@/domain/manufacturing/types";

const TIME_RE =
  /estimated printing time \(normal mode\)\s*=\s*(?:(\d+)d\s*)?(?:(\d+)h\s*)?(?:(\d+)m\s*)?(?:(\d+)s)?/i;
const FILAMENT_MM_RE = /filament used \[mm\]\s*=\s*([0-9.]+)/i;
const FILAMENT_G_RE = /filament used \[g\]\s*=\s*([0-9.]+)/i;
const LAYERS_RE = /total layers count\s*=\s*(\d+)/i;
const ENGINE_RE = /generated by\s+(.+?)\s+on /i;
const SUPPORT_RE = /; support_material\s*=\s*([01])/i;

export class GcodeParseError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "GcodeParseError";
  }
}

function parseDurationSeconds(text: string): number {
  const match = text.match(TIME_RE);
  if (!match) {
    throw new GcodeParseError("G-code içinde tahmini süre yok.");
  }
  const days = Number(match[1] ?? 0);
  const hours = Number(match[2] ?? 0);
  const minutes = Number(match[3] ?? 0);
  const seconds = Number(match[4] ?? 0);
  const duration = days * 86400 + hours * 3600 + minutes * 60 + seconds;
  if (!Number.isFinite(duration) || duration <= 0) {
    throw new GcodeParseError("Tahmini süre geçersiz.");
  }
  return duration;
}

export function parsePrusaGcode(gcode: string): {
  filamentLengthMm: number;
  filamentWeightGrams: number;
  estimatedDurationSeconds: number;
  layerCount: number | null;
  engineVersion: string | null;
  supportHint: boolean | null;
} {
  if (!gcode.includes(";")) {
    throw new GcodeParseError("G-code metadata yorumları yok.");
  }
  const mm = gcode.match(FILAMENT_MM_RE);
  const grams = gcode.match(FILAMENT_G_RE);
  if (!mm || !grams) {
    throw new GcodeParseError("G-code filament metadata'sı yok.");
  }
  const filamentLengthMm = Number(mm[1]);
  const filamentWeightGrams = Number(grams[1]);
  if (!(filamentLengthMm > 0) || !(filamentWeightGrams > 0)) {
    throw new GcodeParseError("Filament miktarı geçersiz.");
  }
  const layers = gcode.match(LAYERS_RE);
  const layerChanges = gcode.match(/;LAYER_CHANGE\b/g);
  const layerCount = layers
    ? Number(layers[1])
    : layerChanges
      ? layerChanges.length
      : null;
  const engine = gcode.match(ENGINE_RE);
  const support = gcode.match(SUPPORT_RE);
  return {
    filamentLengthMm,
    filamentWeightGrams,
    estimatedDurationSeconds: parseDurationSeconds(gcode),
    layerCount,
    engineVersion: engine?.[1]?.trim() ?? null,
    supportHint: support ? support[1] === "1" : null,
  };
}

export function metricsFromGcode(input: {
  gcode: string;
  dimensionsMm: SlicingMetrics["dimensionsMm"];
  materialId: SlicingMetrics["materialId"];
  qualityId: SlicingMetrics["qualityId"];
  quantity: number;
  orientation: SlicingMetrics["orientation"];
  profileChecksum: string;
  supportUsed: boolean;
  warnings: string[];
}): Omit<SlicingMetrics, "engine"> & { engineName: string; engineVersion: string } {
  const parsed = parsePrusaGcode(input.gcode);
  return {
    dimensionsMm: input.dimensionsMm,
    filamentLengthMm: parsed.filamentLengthMm,
    filamentWeightGrams: parsed.filamentWeightGrams,
    estimatedDurationSeconds: parsed.estimatedDurationSeconds,
    layerCount: parsed.layerCount,
    supportUsed: parsed.supportHint ?? input.supportUsed,
    materialId: input.materialId,
    qualityId: input.qualityId,
    quantity: input.quantity,
    orientation: input.orientation,
    profileChecksum: input.profileChecksum,
    warnings: input.warnings,
    engineName: "PrusaSlicer",
    engineVersion: parsed.engineVersion ?? "unknown",
  };
}
