import type { SlicingMetrics } from "@/domain/manufacturing/types";

export const GCODE_PARSER_VERSION = "bc-gcode-support-v1" as const;

const TIME_RE =
  /estimated printing time \(normal mode\)\s*=\s*(?:(\d+)d\s*)?(?:(\d+)h\s*)?(?:(\d+)m\s*)?(?:(\d+)s)?/i;
const FILAMENT_MM_RE = /filament used \[mm\]\s*=\s*([0-9.]+)/i;
const FILAMENT_G_RE = /filament used \[g\]\s*=\s*([0-9.]+)/i;
const LAYERS_RE = /total layers count\s*=\s*(\d+)/i;
const ENGINE_RE = /generated by\s+(.+?)\s+on /i;
const TYPE_RE = /^;TYPE:(.+)$/i;
const LAYER_CHANGE_RE = /^;LAYER_CHANGE\b/;
const EXTRUDE_RE = /(?:^|\s)E(-?\d+(?:\.\d+)?)(?:\s|$)/i;

export class GcodeParseError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "GcodeParseError";
  }
}

function isSupportToolpathType(type: string): boolean {
  const normalized = type.trim().toLowerCase();
  return (
    normalized === "support" ||
    normalized === "support material" ||
    normalized === "support material interface" ||
    normalized.startsWith("support material")
  );
}

function parseDurationSeconds(text: string): number {
  const match = text.match(TIME_RE);
  if (!match) {
    throw new GcodeParseError("G-code içinde tahmini süre yok.");
  }
  const days = Number(match[1] ?? 0);
  const hours = Number(match[2] ?? 0);
  const minutes = Number(match[3] ?? 0);
  const seconds = Number(match[4] ?? 0);
  const duration = days * 86400 + hours * 3600 + minutes * 60 + seconds;
  if (!Number.isFinite(duration) || duration <= 0) {
    throw new GcodeParseError("Tahmini süre geçersiz.");
  }
  return duration;
}

function parseSupportToolpaths(gcode: string): {
  supportGenerated: boolean;
  supportMaterialMm: number;
  supportLayerCount: number;
} {
  let currentType = "";
  let currentLayer = 0;
  let relativeE = true;
  let lastAbsE = 0;
  let supportMaterialMm = 0;
  const supportLayers = new Set<number>();

  for (const raw of gcode.split(/\r?\n/)) {
    const line = raw.trim();
    if (LAYER_CHANGE_RE.test(line)) {
      currentLayer += 1;
      continue;
    }
    const typeMatch = line.match(TYPE_RE);
    if (typeMatch) {
      currentType = typeMatch[1].trim();
      continue;
    }
    if (/^M83\b/i.test(line)) {
      relativeE = true;
      continue;
    }
    if (/^M82\b/i.test(line)) {
      relativeE = false;
      continue;
    }
    if (!/^G[01]\b/i.test(line)) {
      continue;
    }
    const eMatch = line.match(EXTRUDE_RE);
    if (!eMatch) {
      continue;
    }
    const eValue = Number(eMatch[1]);
    if (!Number.isFinite(eValue)) {
      continue;
    }
    const delta = relativeE ? eValue : eValue - lastAbsE;
    lastAbsE = relativeE ? lastAbsE : eValue;
    if (delta > 0 && isSupportToolpathType(currentType)) {
      supportMaterialMm += delta;
      if (currentLayer > 0) {
        supportLayers.add(currentLayer);
      }
    }
  }

  return {
    supportMaterialMm,
    supportLayerCount: supportLayers.size,
    supportGenerated: supportMaterialMm > 0,
  };
}

export function parsePrusaGcode(gcode: string): {
  filamentLengthMm: number;
  filamentWeightGrams: number;
  estimatedDurationSeconds: number;
  layerCount: number | null;
  engineVersion: string | null;
  gcodeParserVersion: typeof GCODE_PARSER_VERSION;
  supportGenerated: boolean;
  supportMaterialMm: number;
  supportMaterialGrams: number;
  supportLayerCount: number;
  supportUsed: boolean;
} {
  if (!gcode.includes(";")) {
    throw new GcodeParseError("G-code metadata yorumları yok.");
  }
  const mm = gcode.match(FILAMENT_MM_RE);
  const grams = gcode.match(FILAMENT_G_RE);
  if (!mm || !grams) {
    throw new GcodeParseError("G-code filament metadata'sı yok.");
  }
  const filamentLengthMm = Number(mm[1]);
  const filamentWeightGrams = Number(grams[1]);
  if (!(filamentLengthMm > 0) || !(filamentWeightGrams > 0)) {
    throw new GcodeParseError("Filament miktarı geçersiz.");
  }
  const layers = gcode.match(LAYERS_RE);
  const layerChanges = gcode.match(/;LAYER_CHANGE\b/g);
  const layerCount = layers
    ? Number(layers[1])
    : layerChanges
      ? layerChanges.length
      : null;
  const engine = gcode.match(ENGINE_RE);
  const support = parseSupportToolpaths(gcode);
  const supportMaterialGrams =
    filamentLengthMm > 0
      ? (filamentWeightGrams * support.supportMaterialMm) / filamentLengthMm
      : 0;
  return {
    filamentLengthMm,
    filamentWeightGrams,
    estimatedDurationSeconds: parseDurationSeconds(gcode),
    layerCount,
    engineVersion: engine?.[1]?.trim() ?? null,
    gcodeParserVersion: GCODE_PARSER_VERSION,
    supportGenerated: support.supportGenerated,
    supportMaterialMm: support.supportMaterialMm,
    supportMaterialGrams,
    supportLayerCount: support.supportLayerCount,
    supportUsed: support.supportGenerated,
  };
}

export function actualSupportGenerated(metrics: {
  supportGenerated?: boolean;
  supportMaterialMm?: number;
  supportUsed?: boolean;
}): boolean {
  if ((metrics.supportMaterialMm ?? 0) > 0) {
    return true;
  }
  if (metrics.supportGenerated === true) {
    return true;
  }
  return false;
}

export function metricsFromGcode(input: {
  gcode: string;
  dimensionsMm: SlicingMetrics["dimensionsMm"];
  materialId: SlicingMetrics["materialId"];
  qualityId: SlicingMetrics["qualityId"];
  quantity: number;
  orientation: SlicingMetrics["orientation"];
  profileChecksum: string;
  warnings: string[];
}): Omit<SlicingMetrics, "engine"> & { engineName: string; engineVersion: string } {
  const parsed = parsePrusaGcode(input.gcode);
  return {
    dimensionsMm: input.dimensionsMm,
    filamentLengthMm: parsed.filamentLengthMm,
    filamentWeightGrams: parsed.filamentWeightGrams,
    estimatedDurationSeconds: parsed.estimatedDurationSeconds,
    layerCount: parsed.layerCount,
    supportUsed: parsed.supportGenerated,
    supportGenerated: parsed.supportGenerated,
    supportMaterialMm: parsed.supportMaterialMm,
    supportMaterialGrams: parsed.supportMaterialGrams,
    supportLayerCount: parsed.supportLayerCount,
    gcodeParserVersion: parsed.gcodeParserVersion,
    materialId: input.materialId,
    qualityId: input.qualityId,
    quantity: input.quantity,
    orientation: input.orientation,
    profileChecksum: input.profileChecksum,
    warnings: input.warnings,
    engineName: "PrusaSlicer",
    engineVersion: parsed.engineVersion ?? "unknown",
  };
}
