import { readFileSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";

import {
  analyzeMesh,
  createAsciiStlTriangle,
  createBinaryStlCube,
  createObjCube,
  detectFormat,
  MeshValidationError,
} from "./mesh";
import { DEVELOPMENT_PRINTER } from "./profiles";

const build = DEVELOPMENT_PRINTER.buildVolumeMm;

describe("mesh validation", () => {
  it("accepts a binary STL cube", () => {
    const bytes = createBinaryStlCube(20);
    expect(detectFormat({ filename: "cube.stl", bytes })).toBe("stl");
    const analysis = analyzeMesh({ filename: "cube.stl", bytes, buildVolumeMm: build });
    expect(analysis.dimensionsMm.x).toBe(20);
    expect(analysis.dimensionsMm.y).toBe(20);
    expect(analysis.dimensionsMm.z).toBe(20);
    expect(analysis.triangleCount).toBe(12);
    expect(analysis.checksumSha256).toMatch(/^[0-9a-f]{64}$/);
  });

  it("accepts ASCII STL", () => {
    const bytes = createAsciiStlTriangle();
    const analysis = analyzeMesh({ filename: "tri.stl", bytes, buildVolumeMm: build });
    expect(analysis.format).toBe("stl");
    expect(analysis.triangleCount).toBe(4);
  });

  it("accepts OBJ cubes", () => {
    const bytes = createObjCube(20);
    const analysis = analyzeMesh({ filename: "cube.obj", bytes, buildVolumeMm: build });
    expect(analysis.format).toBe("obj");
    expect(analysis.dimensionsMm.x).toBe(20);
    expect(analysis.dimensionsMm.y).toBe(20);
    expect(analysis.dimensionsMm.z).toBe(20);
  });

  it("accepts the 20 mm 3MF fixture", () => {
    const bytes = new Uint8Array(
      readFileSync(path.join(process.cwd(), "fixtures", "meshes", "20mm-cube.3mf")),
    );
    const analysis = analyzeMesh({ filename: "cube.3mf", bytes, buildVolumeMm: build });
    expect(analysis.format).toBe("3mf");
    expect(analysis.dimensionsMm.x).toBe(20);
    expect(analysis.dimensionsMm.z).toBe(20);
  });

  it("rejects HTML renamed as STL", () => {
    const bytes = new Uint8Array(Buffer.from("<!DOCTYPE html><html><body>nope</body></html>"));
    expect(() => detectFormat({ filename: "trick.stl", bytes })).toThrow(MeshValidationError);
  });

  it("rejects G-code", () => {
    const bytes = new Uint8Array(Buffer.from("; generated by PrusaSlicer\nG1 X0\n"));
    expect(() => detectFormat({ filename: "job.gcode", bytes })).toThrow(/G-code/);
  });

  it("rejects wrong signatures", () => {
    const bytes = new Uint8Array(Buffer.from("PK\x03\x04notreally"));
    expect(() => detectFormat({ filename: "cube.stl", bytes })).toThrow(MeshValidationError);
  });

  it("flags tiny and huge dimensions", () => {
    const tiny = analyzeMesh({
      filename: "tiny.stl",
      bytes: createBinaryStlCube(0.2),
      buildVolumeMm: build,
    });
    expect(tiny.flags).toContain("extremely_small");
    const huge = analyzeMesh({
      filename: "huge.stl",
      bytes: createBinaryStlCube(400),
      buildVolumeMm: build,
    });
    expect(huge.flags).toContain("does_not_fit");
  });

  it("rejects empty mesh OBJ", () => {
    const bytes = new Uint8Array(Buffer.from("# empty\n"));
    expect(() =>
      analyzeMesh({ filename: "empty.obj", bytes, buildVolumeMm: build }),
    ).toThrow(/OBJ|üçgen|mesh/i);
  });

  it("rejects truncated binary STL", () => {
    const cube = createBinaryStlCube(20);
    const truncated = cube.slice(0, 90);
    expect(() =>
      analyzeMesh({ filename: "cut.stl", bytes: truncated, buildVolumeMm: build }),
    ).toThrow(/STL|uzunluk|kısa|imza/i);
  });

  it("rejects NaN coordinates in ASCII STL", () => {
    const body = `solid test
  facet normal 0 0 1
    outer loop
      vertex NaN 0 0
      vertex 10 0 0
      vertex 0 10 0
    endloop
  endfacet
endsolid test
`;
    expect(() =>
      analyzeMesh({
        filename: "nan.stl",
        bytes: new Uint8Array(Buffer.from(body)),
        buildVolumeMm: build,
      }),
    ).toThrow(/NaN|sonsuz|üçgen|mesh|imza/i);
  });

  it("rejects HTML renamed as STL in analyzeMesh", () => {
    const bytes = new Uint8Array(Buffer.from("<html><body>nope</body></html>"));
    expect(() =>
      analyzeMesh({ filename: "trick.stl", bytes, buildVolumeMm: build }),
    ).toThrow(/HTML/);
  });

  it("rejects G-code renamed as STL", () => {
    const bytes = new Uint8Array(Buffer.from("; generated by PrusaSlicer\nG1 X0 Y0\n"));
    expect(() =>
      analyzeMesh({ filename: "job.stl", bytes, buildVolumeMm: build }),
    ).toThrow(/G-code/);
  });

  it("rejects OBJ mtllib / remote texture references", () => {
    const obj = `mtllib ../../etc/passwd
v 0 0 0
v 10 0 0
v 0 10 0
f 1 2 3
`;
    expect(() =>
      analyzeMesh({
        filename: "evil.obj",
        bytes: new Uint8Array(Buffer.from(obj)),
        buildVolumeMm: build,
      }),
    ).toThrow(/dış|referans/i);
  });

  it("rejects unsupported extensions", () => {
    expect(() =>
      detectFormat({ filename: "model.step", bytes: new Uint8Array([1, 2, 3, 4]) }),
    ).toThrow(/STL|OBJ|3MF|kabul/);
  });

  it("rejects files over 100 MB", () => {
    const bytes = new Uint8Array(100 * 1024 * 1024 + 1);
    expect(() =>
      analyzeMesh({ filename: "huge.stl", bytes, buildVolumeMm: build }),
    ).toThrow(/100 MB/);
  });
});
