import { createHash } from "node:crypto";

import {
  MANUFACTURING_MAX_UPLOAD_BYTES,
  SERVER_TRIANGLE_LIMIT,
  type ManufacturingFormat,
  type MeshAnalysis,
  type MeshUnit,
  type ReviewFlag,
  type Vec3Mm,
} from "@/domain/manufacturing/types";
import { inspectZip, readZipEntry, ZipValidationError } from "@/domain/manufacturing/zip";

export class MeshValidationError extends Error {
  constructor(
    readonly code: string,
    message: string,
  ) {
    super(message);
    this.name = "MeshValidationError";
  }
}

const STL_ASCII_HEAD = "solid";
const HTML_MARKERS = ["<!doctype", "<html", "<head", "<body"];
const GCODE_MARKERS = ["g0 ", "g1 ", "m104", "m109", "; generated by"];

function asciiLower(bytes: Uint8Array, start: number, length: number) {
  return String.fromCharCode(...bytes.slice(start, Math.min(bytes.length, start + length)))
    .toLowerCase();
}

export function sha256Hex(bytes: Uint8Array): string {
  return createHash("sha256").update(bytes).digest("hex");
}

export function detectFormat(input: {
  filename: string;
  bytes: Uint8Array;
  declaredMime?: string | null;
}): ManufacturingFormat {
  const name = input.filename.toLocaleLowerCase("tr-TR");
  const head = asciiLower(input.bytes, 0, 64).replace(/\0/g, " ").trim();

  if (HTML_MARKERS.some((marker) => head.includes(marker))) {
    throw new MeshValidationError("html_disguised", "Dosya HTML belgesi; mesh değil.");
  }
  if (GCODE_MARKERS.some((marker) => head.includes(marker)) || name.endsWith(".gcode") || name.endsWith(".gco")) {
    throw new MeshValidationError("gcode_rejected", "Müşteri G-code dosyası kabul edilmez.");
  }

  const isZip =
    input.bytes[0] === 0x50 &&
    input.bytes[1] === 0x4b &&
    input.bytes[2] === 0x03 &&
    input.bytes[3] === 0x04;

  if (name.endsWith(".3mf") || input.declaredMime === "model/3mf" || input.declaredMime === "application/vnd.ms-package.3dmanufacturing-3dmodel+xml") {
    if (!isZip) {
      throw new MeshValidationError("signature", "3MF ZIP imzası yok.");
    }
    return "3mf";
  }

  if (name.endsWith(".obj") || input.declaredMime === "model/obj" || input.declaredMime === "text/plain") {
    if (isLikelyObj(input.bytes)) {
      return "obj";
    }
    if (name.endsWith(".obj")) {
      throw new MeshValidationError("signature", "OBJ içeriği beklenen yapıda değil.");
    }
  }

  if (name.endsWith(".stl") || input.declaredMime === "model/stl" || input.declaredMime === "application/sla") {
    if (isLikelyStl(input.bytes)) {
      return "stl";
    }
    throw new MeshValidationError("signature", "STL imzası veya üçgen tablosu geçersiz.");
  }

  if (isZip) {
    throw new MeshValidationError("unsupported", "ZIP yalnızca 3MF olarak kabul edilir.");
  }
  if (isLikelyStl(input.bytes)) {
    return "stl";
  }
  if (isLikelyObj(input.bytes)) {
    return "obj";
  }

  throw new MeshValidationError("unsupported", "Yalnızca STL, OBJ veya 3MF kabul edilir.");
}

function isLikelyObj(bytes: Uint8Array) {
  const sample = asciiLower(bytes, 0, Math.min(bytes.length, 2048));
  return /(^|\n)\s*(v|vn|vt|f|o|g)\s/.test(sample);
}

function isLikelyStl(bytes: Uint8Array) {
  if (bytes.length < 84) {
    return asciiLower(bytes, 0, 5) === STL_ASCII_HEAD && asciiLower(bytes, 0, 256).includes("facet");
  }
  if (asciiLower(bytes, 0, 5) === STL_ASCII_HEAD && asciiLower(bytes, 0, 512).includes("facet")) {
    return true;
  }
  const triangles = bytes[80]! | (bytes[81]! << 8) | (bytes[82]! << 16) | (bytes[83]! << 24);
  return triangles > 0 && bytes.length === 84 + triangles * 50;
}

function readFloat(view: DataView, offset: number) {
  const value = view.getFloat32(offset, true);
  if (!Number.isFinite(value)) {
    throw new MeshValidationError("invalid_coordinates", "NaN veya sonsuz koordinat var.");
  }
  return value;
}

export function unitScale(unit: MeshUnit, customScale: number | null): number {
  if (unit === "mm") {
    return 1;
  }
  if (unit === "cm") {
    return 10;
  }
  if (unit === "m") {
    return 1000;
  }
  if (customScale && customScale > 0 && Number.isFinite(customScale)) {
    return customScale;
  }
  throw new MeshValidationError("unit", "Özel ölçek pozitif bir sayı olmalıdır.");
}

export function analyzeMesh(input: {
  filename: string;
  bytes: Uint8Array;
  declaredMime?: string | null;
  unit?: MeshUnit;
  customScale?: number | null;
  scalePercent?: number;
  buildVolumeMm: Vec3Mm;
}): MeshAnalysis {
  if (input.bytes.byteLength === 0) {
    throw new MeshValidationError("empty", "Dosya boş olamaz.");
  }
  if (input.bytes.byteLength > MANUFACTURING_MAX_UPLOAD_BYTES) {
    throw new MeshValidationError("too_large", "Dosya 100 MB sınırını aşıyor.");
  }

  const format = detectFormat(input);
  const scalePercent = input.scalePercent ?? 100;
  if (!(scalePercent > 0) || scalePercent > 1000) {
    throw new MeshValidationError("scale", "Ölçek 0 ile 1000 arasında olmalıdır.");
  }
  const toMm = unitScale(input.unit ?? "mm", input.customScale ?? null) * (scalePercent / 100);

  let vertices: Vec3Mm[] = [];
  let triangleCount = 0;
  let degenerateFaces = 0;
  let shellCount = 1;

  if (format === "stl") {
    const parsed = parseStl(input.bytes);
    vertices = parsed.vertices;
    triangleCount = parsed.triangleCount;
    degenerateFaces = parsed.degenerateFaces;
  } else if (format === "obj") {
    const parsed = parseObj(input.bytes);
    vertices = parsed.vertices;
    triangleCount = parsed.triangleCount;
    degenerateFaces = parsed.degenerateFaces;
  } else {
    const parsed = parse3mf(input.bytes);
    vertices = parsed.vertices;
    triangleCount = parsed.triangleCount;
    shellCount = parsed.shellCount;
  }

  if (triangleCount === 0 || vertices.length === 0) {
    throw new MeshValidationError("empty_mesh", "Mesh üçgen veya tepe içermiyor.");
  }
  if (triangleCount > SERVER_TRIANGLE_LIMIT) {
    throw new MeshValidationError("triangle_limit", "Üçgen sayısı sunucu sınırını aşıyor.");
  }

  const min = { x: Infinity, y: Infinity, z: Infinity };
  const max = { x: -Infinity, y: -Infinity, z: -Infinity };
  for (const vertex of vertices) {
    min.x = Math.min(min.x, vertex.x * toMm);
    min.y = Math.min(min.y, vertex.y * toMm);
    min.z = Math.min(min.z, vertex.z * toMm);
    max.x = Math.max(max.x, vertex.x * toMm);
    max.y = Math.max(max.y, vertex.y * toMm);
    max.z = Math.max(max.z, vertex.z * toMm);
  }

  const dimensionsMm = {
    x: round3(max.x - min.x),
    y: round3(max.y - min.y),
    z: round3(max.z - min.z),
  };
  const volumeMm3 = approximateVolume(dimensionsMm);
  const flags: ReviewFlag[] = [];

  if (degenerateFaces > 0) {
    flags.push("non_manifold");
  }
  if (shellCount > 1) {
    flags.push("multiple_shells");
  }
  if (Math.min(dimensionsMm.x, dimensionsMm.y, dimensionsMm.z) < 0.4) {
    flags.push("thin_features");
  }
  if (Math.max(dimensionsMm.x, dimensionsMm.y, dimensionsMm.z) < 1) {
    flags.push("extremely_small");
    flags.push("implausible_units");
  }
  if (Math.max(dimensionsMm.x, dimensionsMm.y, dimensionsMm.z) > 1000) {
    flags.push("extremely_large");
    flags.push("implausible_units");
  }
  const fitsBuildVolume =
    dimensionsMm.x <= input.buildVolumeMm.x &&
    dimensionsMm.y <= input.buildVolumeMm.y &&
    dimensionsMm.z <= input.buildVolumeMm.z;
  if (!fitsBuildVolume) {
    flags.push("does_not_fit");
  }
  if (triangleCount > 250_000) {
    flags.push("high_triangle_count");
  }
  if (volumeMm3 !== null && volumeMm3 <= 0) {
    throw new MeshValidationError("zero_volume", "Sıfır hacimli mesh kabul edilmez.");
  }

  return {
    format,
    triangleCount,
    vertexCount: vertices.length,
    shellCount,
    boundingBoxMm: { min: roundVec(min), max: roundVec(max) },
    dimensionsMm,
    volumeMm3,
    manifold: degenerateFaces === 0 ? null : false,
    watertight: null,
    degenerateFaces,
    hasInvalidCoordinates: false,
    fitsBuildVolume,
    scalePercent,
    checksumSha256: sha256Hex(input.bytes),
    unitAssumed: input.unit ?? "mm",
    flags,
  };
}

function round3(value: number) {
  return Math.round(value * 1000) / 1000;
}

function roundVec(value: Vec3Mm): Vec3Mm {
  return { x: round3(value.x), y: round3(value.y), z: round3(value.z) };
}

function approximateVolume(dimensions: Vec3Mm): number | null {
  const volume = dimensions.x * dimensions.y * dimensions.z;
  if (!Number.isFinite(volume) || volume < 0) {
    return null;
  }
  return round3(volume);
}

function parseStl(bytes: Uint8Array) {
  const head = asciiLower(bytes, 0, 5);
  const looksAscii = head === STL_ASCII_HEAD && asciiLower(bytes, 0, 512).includes("facet");
  if (looksAscii) {
    return parseAsciiStl(bytes);
  }
  return parseBinaryStl(bytes);
}

function parseBinaryStl(bytes: Uint8Array) {
  if (bytes.length < 84) {
    throw new MeshValidationError("corrupt", "Binary STL çok kısa.");
  }
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  const triangleCount = view.getUint32(80, true);
  if (bytes.length !== 84 + triangleCount * 50) {
    throw new MeshValidationError("corrupt", "Binary STL uzunluğu üçgen sayısıyla uyuşmuyor.");
  }
  const vertices: Vec3Mm[] = [];
  let degenerateFaces = 0;
  for (let index = 0; index < triangleCount; index += 1) {
    const base = 84 + index * 50 + 12;
    const a = {
      x: readFloat(view, base),
      y: readFloat(view, base + 4),
      z: readFloat(view, base + 8),
    };
    const b = {
      x: readFloat(view, base + 12),
      y: readFloat(view, base + 16),
      z: readFloat(view, base + 20),
    };
    const c = {
      x: readFloat(view, base + 24),
      y: readFloat(view, base + 28),
      z: readFloat(view, base + 32),
    };
    if (sameVertex(a, b) || sameVertex(b, c) || sameVertex(a, c)) {
      degenerateFaces += 1;
    }
    vertices.push(a, b, c);
  }
  return { vertices, triangleCount, degenerateFaces };
}

function parseAsciiStl(bytes: Uint8Array) {
  const text = Buffer.from(bytes).toString("utf8");
  if (!/endsolid/i.test(text)) {
    throw new MeshValidationError("corrupt", "ASCII STL kapanışı yok.");
  }
  const vertices: Vec3Mm[] = [];
  const vertexPattern = /vertex\s+([+-]?(?:\d+\.?\d*|\.\d+)(?:[eE][+-]?\d)?)\s+([+-]?(?:\d+\.?\d*|\.\d+)(?:[eE][+-]?\d)?)\s+([+-]?(?:\d+\.?\d*|\.\d+)(?:[eE][+-]?\d)?)/g;
  let match: RegExpExecArray | null;
  while ((match = vertexPattern.exec(text))) {
    const point = {
      x: Number(match[1]),
      y: Number(match[2]),
      z: Number(match[3]),
    };
    if (![point.x, point.y, point.z].every(Number.isFinite)) {
      throw new MeshValidationError("invalid_coordinates", "NaN veya sonsuz koordinat var.");
    }
    vertices.push(point);
  }
  const triangleCount = Math.floor(vertices.length / 3);
  if (triangleCount === 0) {
    throw new MeshValidationError("empty_mesh", "ASCII STL üçgen içermiyor.");
  }
  return { vertices, triangleCount, degenerateFaces: vertices.length % 3 === 0 ? 0 : 1 };
}

function parseObj(bytes: Uint8Array) {
  const text = Buffer.from(bytes).toString("utf8");
  const vertices: Vec3Mm[] = [];
  let triangleCount = 0;
  let degenerateFaces = 0;
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (line.startsWith("v ")) {
      const parts = line.slice(2).trim().split(/\s+/);
      const point = { x: Number(parts[0]), y: Number(parts[1]), z: Number(parts[2]) };
      if (![point.x, point.y, point.z].every(Number.isFinite)) {
        throw new MeshValidationError("invalid_coordinates", "NaN veya sonsuz koordinat var.");
      }
      vertices.push(point);
    } else if (/^mtllib\s/i.test(line) || /^map_/i.test(line) || /https?:|file:/i.test(line)) {
      throw new MeshValidationError(
        "external_reference",
        "OBJ dış dosya veya malzeme referansı kabul edilmez.",
      );
    } else if (line.startsWith("f ")) {
      const corners = line.slice(2).trim().split(/\s+/);
      if (corners.length < 3) {
        degenerateFaces += 1;
      } else {
        triangleCount += corners.length - 2;
      }
    }
  }
  return { vertices, triangleCount, degenerateFaces };
}

function parse3mf(bytes: Uint8Array) {
  let entries;
  try {
    entries = inspectZip(bytes);
  } catch (error) {
    if (error instanceof ZipValidationError) {
      throw new MeshValidationError("archive", error.message);
    }
    throw error;
  }
  const modelEntry = entries.find((entry) => /3d\/.*\.model$/i.test(entry.name) || entry.name.endsWith("3dmodel.model"));
  if (!modelEntry) {
    throw new MeshValidationError("empty_mesh", "3MF içinde model geometrisi yok.");
  }
  const xml = Buffer.from(readZipEntry(bytes, modelEntry)).toString("utf8");
  const vertices: Vec3Mm[] = [];
  const vertexPattern = /<vertex\b[^>]*\bx=["']([^"']+)["'][^>]*\by=["']([^"']+)["'][^>]*\bz=["']([^"']+)["']/gi;
  let match: RegExpExecArray | null;
  while ((match = vertexPattern.exec(xml))) {
    const point = { x: Number(match[1]), y: Number(match[2]), z: Number(match[3]) };
    if (![point.x, point.y, point.z].every(Number.isFinite)) {
      throw new MeshValidationError("invalid_coordinates", "NaN veya sonsuz koordinat var.");
    }
    vertices.push(point);
  }
  const triangleCount = (xml.match(/<triangle\b/gi) ?? []).length;
  const shellCount = Math.max(1, (xml.match(/<object\b/gi) ?? []).length);
  return { vertices, triangleCount, shellCount };
}

function sameVertex(a: Vec3Mm, b: Vec3Mm) {
  return a.x === b.x && a.y === b.y && a.z === b.z;
}

export function createBinaryStlCube(sizeMm: number, origin: Vec3Mm = { x: 0, y: 0, z: 0 }): Uint8Array {
  const s = sizeMm;
  const o = origin;
  const faces: Array<[Vec3Mm, Vec3Mm, Vec3Mm]> = [
    [{ x: o.x, y: o.y, z: o.z }, { x: o.x + s, y: o.y, z: o.z }, { x: o.x + s, y: o.y + s, z: o.z }],
    [{ x: o.x, y: o.y, z: o.z }, { x: o.x + s, y: o.y + s, z: o.z }, { x: o.x, y: o.y + s, z: o.z }],
    [{ x: o.x, y: o.y, z: o.z + s }, { x: o.x + s, y: o.y + s, z: o.z + s }, { x: o.x + s, y: o.y, z: o.z + s }],
    [{ x: o.x, y: o.y, z: o.z + s }, { x: o.x, y: o.y + s, z: o.z + s }, { x: o.x + s, y: o.y + s, z: o.z + s }],
    [{ x: o.x, y: o.y, z: o.z }, { x: o.x, y: o.y, z: o.z + s }, { x: o.x + s, y: o.y, z: o.z + s }],
    [{ x: o.x, y: o.y, z: o.z }, { x: o.x + s, y: o.y, z: o.z + s }, { x: o.x + s, y: o.y, z: o.z }],
    [{ x: o.x, y: o.y + s, z: o.z }, { x: o.x + s, y: o.y + s, z: o.z }, { x: o.x + s, y: o.y + s, z: o.z + s }],
    [{ x: o.x, y: o.y + s, z: o.z }, { x: o.x + s, y: o.y + s, z: o.z + s }, { x: o.x, y: o.y + s, z: o.z + s }],
    [{ x: o.x, y: o.y, z: o.z }, { x: o.x, y: o.y + s, z: o.z }, { x: o.x, y: o.y + s, z: o.z + s }],
    [{ x: o.x, y: o.y, z: o.z }, { x: o.x, y: o.y + s, z: o.z + s }, { x: o.x, y: o.y, z: o.z + s }],
    [{ x: o.x + s, y: o.y, z: o.z }, { x: o.x + s, y: o.y, z: o.z + s }, { x: o.x + s, y: o.y + s, z: o.z + s }],
    [{ x: o.x + s, y: o.y, z: o.z }, { x: o.x + s, y: o.y + s, z: o.z + s }, { x: o.x + s, y: o.y + s, z: o.z }],
  ];
  const buffer = Buffer.alloc(84 + faces.length * 50);
  buffer.write("Baski Ciftligi fixture", 0, "ascii");
  buffer.writeUInt32LE(faces.length, 80);
  faces.forEach((face, index) => {
    const offset = 84 + index * 50;
    writeVertex(buffer, offset + 12, face[0]);
    writeVertex(buffer, offset + 24, face[1]);
    writeVertex(buffer, offset + 36, face[2]);
  });
  return new Uint8Array(buffer);
}

function writeVertex(buffer: Buffer, offset: number, vertex: Vec3Mm) {
  buffer.writeFloatLE(vertex.x, offset);
  buffer.writeFloatLE(vertex.y, offset + 4);
  buffer.writeFloatLE(vertex.z, offset + 8);
}

export function createAsciiStlTriangle(): Uint8Array {
  const body = `solid test
  facet normal 0 0 1
    outer loop
      vertex 0 0 0
      vertex 10 0 0
      vertex 0 10 0
    endloop
  endfacet
  facet normal 0 1 0
    outer loop
      vertex 0 0 0
      vertex 0 10 0
      vertex 0 0 10
    endloop
  endfacet
  facet normal 1 0 0
    outer loop
      vertex 0 0 0
      vertex 0 0 10
      vertex 10 0 0
    endloop
  endfacet
  facet normal 0.577 0.577 0.577
    outer loop
      vertex 10 0 0
      vertex 0 10 0
      vertex 0 0 10
    endloop
  endfacet
endsolid test
`;
  return new Uint8Array(Buffer.from(body, "utf8"));
}

export function createObjCube(sizeMm: number): Uint8Array {
  const s = sizeMm;
  const body = [
    `v 0 0 0`,
    `v ${s} 0 0`,
    `v ${s} ${s} 0`,
    `v 0 ${s} 0`,
    `v 0 0 ${s}`,
    `v ${s} 0 ${s}`,
    `v ${s} ${s} ${s}`,
    `v 0 ${s} ${s}`,
    `f 1 2 3`,
    `f 1 3 4`,
    `f 5 8 7`,
    `f 5 7 6`,
    `f 1 5 6`,
    `f 1 6 2`,
    `f 4 3 7`,
    `f 4 7 8`,
    `f 1 4 8`,
    `f 1 8 5`,
    `f 2 6 7`,
    `f 2 7 3`,
    "",
  ].join("\n");
  return new Uint8Array(Buffer.from(body, "utf8"));
}

