import type { Product } from "@/domain/catalog/types";
import type { ProductFormInput } from "@/lib/validation/catalog";

export function createEmptyProductForm(): ProductFormInput {
  return {
    id: crypto.randomUUID(),
    name: "",
    slug: "",
    shortDescription: "",
    description: "",
    status: "draft",
    kind: "made_to_order",
    priceMinor: 0,
    compareAtPriceMinor: null,
    sku: "",
    barcode: "",
    productionLeadTimeMinDays: 2,
    productionLeadTimeMaxDays: 5,
    categorySlugs: [],
    collectionSlugs: [],
    featured: false,
    vatRateBps: 2000,
    inventoryPolicy: "deny",
    materialCode: "",
    materialSummary: "",
    weightGrams: null,
    widthMm: null,
    depthMm: null,
    heightMm: null,
    personalizationEnabled: false,
    personalizationFields: [],
    sortOrder: 0,
    canonicalUrl: "",
    searchVisible: true,
    noindex: false,
    modelName: "",
    themeStyle: "",
    stagePreset: "",
    objectPosition: "",
    mobileObjectPosition: "",
    isolated: false,
    badges: [],
    publishedAt: "",
    seoTitle: "",
    seoDescription: "",
    media: [],
    variants: [
      {
        name: "Standart",
        sku: "",
        colorName: "",
        colorHex: "",
        priceAdjustmentMinor: 0,
        inventoryQuantity: 0,
        isActive: true,
      },
    ],
  };
}

export function productToAdminForm(product: Product): ProductFormInput {
  return {
    id: product.id,
    name: product.name,
    slug: product.slug,
    shortDescription: product.shortDescription,
    description: product.description,
    status: product.status,
    kind: product.kind,
    priceMinor: product.priceMinor,
    compareAtPriceMinor: product.compareAtPriceMinor,
    sku: product.sku,
    barcode: product.barcode ?? "",
    productionLeadTimeMinDays: product.productionLeadTimeDays.min,
    productionLeadTimeMaxDays: product.productionLeadTimeDays.max,
    categorySlugs: product.categorySlugs,
    collectionSlugs: product.collectionSlugs,
    featured: product.featured,
    vatRateBps: product.vatRateBps ?? 2000,
    inventoryPolicy: product.inventoryPolicy ?? "deny",
    materialCode: product.materialCode ?? "",
    materialSummary: product.materialSummary ?? "",
    weightGrams: product.weightGrams ?? null,
    widthMm: product.widthMm ?? null,
    depthMm: product.depthMm ?? null,
    heightMm: product.heightMm ?? null,
    personalizationEnabled: product.personalizationEnabled ?? false,
    personalizationFields: product.personalizationFields ?? [],
    sortOrder: product.sortOrder ?? 0,
    canonicalUrl: product.canonicalUrl ?? "",
    searchVisible: product.searchVisible ?? true,
    noindex: product.noindex ?? false,
    modelName: product.modelName ?? "",
    themeStyle: product.themeStyle ?? "",
    stagePreset: product.presentation?.stagePreset ?? "",
    objectPosition: product.presentation?.objectPosition ?? "",
    mobileObjectPosition: product.presentation?.mobileObjectPosition ?? "",
    isolated: product.presentation?.isolated ?? false,
    badges: product.badges,
    publishedAt: product.publishedAt ?? "",
    seoTitle: product.seoTitle,
    seoDescription: product.seoDescription,
    media: product.media.map((media, index) => ({
      id: media.id,
      url: media.url,
      alt: media.alt,
      position: index,
      role: media.role,
      objectPosition: media.objectPosition ?? "",
      mobileObjectPosition: media.mobileObjectPosition ?? "",
      isolated: media.isolated,
      variantId: media.variantId ?? "",
      storagePath: media.storagePath ?? "",
      mimeType: media.mimeType ?? "",
    })),
    variants: product.variants.map((variant) => ({
      id: variant.id,
      name: variant.name,
      sku: variant.sku,
      colorName: variant.colorName ?? "",
      colorHex: variant.colorHex ?? "",
      material: variant.material ?? "",
      sizeLabel: variant.sizeLabel ?? "",
      barcode: variant.barcode ?? "",
      priceAdjustmentMinor: variant.priceAdjustmentMinor,
      inventoryQuantity: variant.inventoryQuantity,
      isActive: variant.isActive,
    })),
  };
}
