import type { Product } from "@/domain/catalog/types";
import type { ProductFormInput } from "@/lib/validation/catalog";

export function createEmptyProductForm(): ProductFormInput {
  return {
    name: "",
    slug: "",
    shortDescription: "",
    description: "",
    status: "draft",
    kind: "made_to_order",
    priceMinor: 0,
    compareAtPriceMinor: null,
    sku: "",
    barcode: "",
    productionLeadTimeMinDays: 2,
    productionLeadTimeMaxDays: 5,
    categorySlugs: [],
    collectionSlugs: [],
    featured: false,
    stagePreset: "",
    objectPosition: "",
    mobileObjectPosition: "",
    isolated: false,
    badges: [],
    publishedAt: "",
    seoTitle: "",
    seoDescription: "",
    media: [],
    variants: [
      {
        name: "Standart",
        sku: "",
        colorName: "",
        colorHex: "",
        priceAdjustmentMinor: 0,
        inventoryQuantity: 0,
        isActive: true,
      },
    ],
  };
}

export function productToAdminForm(product: Product): ProductFormInput {
  return {
    id: product.id,
    name: product.name,
    slug: product.slug,
    shortDescription: product.shortDescription,
    description: product.description,
    status: product.status,
    kind: product.kind,
    priceMinor: product.priceMinor,
    compareAtPriceMinor: product.compareAtPriceMinor,
    sku: product.sku,
    barcode: product.barcode ?? "",
    productionLeadTimeMinDays: product.productionLeadTimeDays.min,
    productionLeadTimeMaxDays: product.productionLeadTimeDays.max,
    categorySlugs: product.categorySlugs,
    collectionSlugs: product.collectionSlugs,
    featured: product.featured,
    stagePreset: product.presentation?.stagePreset ?? "",
    objectPosition: product.presentation?.objectPosition ?? "",
    mobileObjectPosition: product.presentation?.mobileObjectPosition ?? "",
    isolated: product.presentation?.isolated ?? false,
    badges: product.badges,
    publishedAt: product.publishedAt ?? "",
    seoTitle: product.seoTitle,
    seoDescription: product.seoDescription,
    media: product.media.map((media, index) => ({
      id: media.id,
      url: media.url,
      alt: media.alt,
      position: index,
      role: media.role,
      objectPosition: media.objectPosition ?? "",
      mobileObjectPosition: media.mobileObjectPosition ?? "",
      isolated: media.isolated,
    })),
    variants: product.variants.map((variant) => ({
      id: variant.id,
      name: variant.name,
      sku: variant.sku,
      colorName: variant.colorName ?? "",
      colorHex: variant.colorHex ?? "",
      priceAdjustmentMinor: variant.priceAdjustmentMinor,
      inventoryQuantity: variant.inventoryQuantity,
      isActive: variant.isActive,
    })),
  };
}
