import { siteConfig } from "@/config/site";
import type {
  Announcement,
  CatalogSnapshot,
  Category,
  Collection,
  Material,
  Product,
  ProductVariant,
} from "./types";

const makeVariants = (
  productKey: string,
  colors: Array<[string, string]>,
  stock = 12,
): ProductVariant[] =>
  colors.map(([name, hex], index) => ({
    id: `demo-variant-${productKey}-${index + 1}`,
    name,
    sku: `DEMO-${productKey.toUpperCase()}-${index + 1}`,
    colorName: name,
    colorHex: hex,
    priceAdjustmentMinor: 0,
    inventoryQuantity: stock,
    isActive: true,
  }));

export const demoCategories: Category[] = [
  {
    id: "demo-category-home",
    slug: "ev-ve-dekorasyon",
    name: "Ev ve Dekorasyon",
    description: "Katman dokusunu tasarımın parçasına dönüştüren çağdaş objeler.",
    imageUrl: "/demo/categories/dekorasyon.svg",
    eyebrow: "Yaşam alanları",
    isFeatured: true,
    position: 1,
    isDemo: true,
  },
  {
    id: "demo-category-sculpture",
    slug: "biblo-ve-heykel",
    name: "Biblo ve Heykel",
    description: "Dijital heykelden fiziksel koleksiyon parçasına.",
    imageUrl: "/demo/categories/heykel.svg",
    eyebrow: "Koleksiyon",
    isFeatured: true,
    position: 2,
    isDemo: true,
  },
  {
    id: "demo-category-desk",
    slug: "masaustu-aksesuarlari",
    name: "Masaüstü Aksesuarları",
    description: "Odaklanmış çalışma alanları için işlevsel tasarımlar.",
    imageUrl: "/demo/categories/masaustu.svg",
    eyebrow: "Çalışma alanı",
    isFeatured: true,
    position: 3,
    isDemo: true,
  },
  {
    id: "demo-category-personal",
    slug: "kisiye-ozel-urunler",
    name: "Kişiye Özel Ürünler",
    description: "İsim, ölçü ve renk seçenekleriyle size özel üretim.",
    imageUrl: "/demo/categories/kisiye-ozel.svg",
    eyebrow: "Size özel",
    isFeatured: true,
    position: 4,
    isDemo: true,
  },
  {
    id: "demo-category-functional",
    slug: "fonksiyonel-parcalar",
    name: "Fonksiyonel Parçalar",
    description: "Günlük sorunlara ölçülü, dayanıklı ve tekrarlanabilir çözümler.",
    imageUrl: "/demo/categories/fonksiyonel.svg",
    eyebrow: "Mühendislik",
    isFeatured: true,
    position: 5,
    isDemo: true,
  },
  {
    id: "demo-category-keychain",
    slug: "anahtarlik",
    name: "Anahtarlık",
    description: "Kompakt, kişiselleştirilebilir günlük objeler.",
    imageUrl: "/demo/categories/anahtarlik.svg",
    eyebrow: "Küçük seri",
    isFeatured: false,
    position: 6,
    isDemo: true,
  },
  {
    id: "demo-category-magnet",
    slug: "magnet",
    name: "Magnet",
    description: "Markalar, etkinlikler ve özel günler için özgün tasarımlar.",
    imageUrl: "/demo/categories/magnet.svg",
    eyebrow: "Hatıra",
    isFeatured: false,
    position: 7,
    isDemo: true,
  },
  {
    id: "demo-category-events",
    slug: "organizasyon-urunleri",
    name: "Organizasyon Ürünleri",
    description: "Davet, masa düzeni ve etkinlikler için kişiselleştirme.",
    imageUrl: "/demo/categories/dekorasyon.svg",
    eyebrow: "Etkinlik",
    isFeatured: false,
    position: 8,
    isDemo: true,
  },
  {
    id: "demo-category-corporate",
    slug: "kurumsal-promosyon",
    name: "Kurumsal Promosyon",
    description: "Markanıza göre tasarlanan, seri üretime uygun ürünler.",
    imageUrl: "/demo/categories/kurumsal.svg",
    eyebrow: "B2B",
    isFeatured: false,
    position: 9,
    isDemo: true,
  },
  {
    id: "demo-category-new",
    slug: "yeni-gelenler",
    name: "Yeni Gelenler",
    description: "Stüdyodan çıkan en yeni denemeler ve sınırlı seriler.",
    imageUrl: "/demo/categories/heykel.svg",
    eyebrow: "Yeni",
    isFeatured: false,
    position: 10,
    isDemo: true,
  },
];

export const demoProducts: Product[] = [
  {
    id: "demo-product-vase-01",
    slug: "flux-vazo-demo",
    name: "Flux Vazo — Demo",
    shortDescription: "Işığı katmanlar boyunca kıran parametrik masa vazosu.",
    description:
      "Flux, tek bir sürekli yüzeyden oluşan parametrik formuyla gün ışığında farklı gölgeler üretir. Bitki kullanımı için iç hazne ayrıca gönderilir. Bu kayıt yalnızca geliştirme ve mağaza sunumu için demo veridir.",
    status: "active",
    kind: "made_to_order",
    priceMinor: 84900,
    compareAtPriceMinor: null,
    currency: "TRY",
    sku: "DEMO-FLX-01",
    inventoryQuantity: 24,
    productionLeadTimeDays: { min: 2, max: 4 },
    categorySlugs: ["ev-ve-dekorasyon", "yeni-gelenler"],
    collectionSlugs: ["cok-satanlar", "yeni-urunler"],
    media: [
      {
        id: "demo-media-vase-1",
        type: "image",
        url: "/demo/products/flux-vazo.svg",
        alt: "Flux vazo demo ürün görseli",
        position: 1,
        role: "primary",
        isolated: true,
        objectPosition: "50% 42%",
      },
      {
        id: "demo-media-vase-2",
        type: "image",
        url: "/demo/products/flux-vazo-detail.svg",
        alt: "Flux vazo katman detayı demo görseli",
        position: 2,
        role: "hover",
        isolated: false,
      },
    ],
    variants: makeVariants("flux", [
      ["Kemik", "#DED7C8"],
      ["Gece", "#171A1D"],
      ["Kobalt", "#174B66"],
    ]),
    presentation: {
      stagePreset: "cyan",
      isolated: true,
      objectPosition: "50% 42%",
    },
    badges: ["new", "bestseller"],
    featured: true,
    seoTitle: `Flux Parametrik Vazo | ${siteConfig.name}`,
    seoDescription: "Çağdaş parametrik form, isteğe göre üretilen Flux vazo.",
    publishedAt: "2026-08-01T09:00:00.000Z",
    isDemo: true,
    reviewSummary: { average: 4.8, count: 12, isDemo: true },
  },
  {
    id: "demo-product-lamp-01",
    slug: "orbit-ambiyans-lambasi-demo",
    name: "Orbit Ambiyans Lambası — Demo",
    shortDescription: "Dolaylı ışık için katmanlı, heykelsi masa lambası.",
    description:
      "Orbit, ışık kaynağını doğrudan göstermeden sıcak bir ambiyans oluşturmak üzere tasarlanmıştır. Elektrik aksamı test edilmiş modül olarak sağlanır. Demo katalog kaydıdır.",
    status: "active",
    kind: "made_to_order",
    priceMinor: 164900,
    compareAtPriceMinor: 189900,
    currency: "TRY",
    sku: "DEMO-ORB-01",
    inventoryQuantity: 8,
    productionLeadTimeDays: { min: 3, max: 5 },
    categorySlugs: ["ev-ve-dekorasyon"],
    collectionSlugs: ["cok-satanlar", "sinirli-uretim"],
    media: [
      {
        id: "demo-media-lamp-1",
        type: "image",
        url: "/demo/products/orbit-lamba.svg",
        alt: "Orbit masa lambası demo ürün görseli",
        position: 1,
        role: "primary",
        isolated: true,
      },
    ],
    variants: makeVariants(
      "orbit",
      [
        ["Kum", "#C9B99A"],
        ["Grafit", "#343A40"],
      ],
      8,
    ),
    badges: ["bestseller", "limited"],
    featured: true,
    seoTitle: `Orbit 3D Baskı Ambiyans Lambası | ${siteConfig.name}`,
    seoDescription: "Katmanlı yüzeyiyle yumuşak ışık sunan Orbit masa lambası.",
    publishedAt: "2026-07-18T09:00:00.000Z",
    isDemo: true,
    reviewSummary: { average: 4.6, count: 9, isDemo: true },
  },
  {
    id: "demo-product-headphone-01",
    slug: "arc-kulaklik-standi-demo",
    name: "Arc Kulaklık Standı — Demo",
    shortDescription: "Kulaklık formunu destekleyen dengeli masaüstü standı.",
    description:
      "Arc, geniş tabanı ve kablo kanalıyla çalışma alanını düzenler. PETG seçeneği darbelere ve günlük kullanıma uygundur. Demo katalog kaydıdır.",
    status: "active",
    kind: "ready_stock",
    priceMinor: 69900,
    compareAtPriceMinor: null,
    currency: "TRY",
    sku: "DEMO-ARC-01",
    inventoryQuantity: 18,
    productionLeadTimeDays: { min: 1, max: 2 },
    categorySlugs: ["masaustu-aksesuarlari", "fonksiyonel-parcalar"],
    collectionSlugs: ["cok-satanlar", "sana-ozel"],
    media: [
      {
        id: "demo-media-arc-1",
        type: "image",
        url: "/demo/products/arc-stand.svg",
        alt: "Arc kulaklık standı demo görseli",
        position: 1,
        role: "primary",
        isolated: true,
      },
    ],
    variants: makeVariants("arc", [
      ["Siyah", "#16191D"],
      ["Taş", "#A7A397"],
      ["Turuncu", "#D95E2B"],
    ]),
    badges: ["bestseller"],
    featured: true,
    seoTitle: `Arc Kulaklık Standı | ${siteConfig.name}`,
    seoDescription: "Kablo kanallı, dengeli ve sade Arc kulaklık standı.",
    publishedAt: "2026-06-12T09:00:00.000Z",
    isDemo: true,
  },
  {
    id: "demo-product-planter-01",
    slug: "tidal-saksi-demo",
    name: "Tidal Saksı — Demo",
    shortDescription: "Dalga ritminden ilham alan modüler saksı ve altlık.",
    description:
      "Tidal saksı, çıkarılabilir iç haznesi ve taşmayı azaltan taban geometrisiyle masaüstü bitkileri için tasarlandı. Demo katalog kaydıdır.",
    status: "active",
    kind: "made_to_order",
    priceMinor: 57900,
    compareAtPriceMinor: null,
    currency: "TRY",
    sku: "DEMO-TDL-01",
    inventoryQuantity: 30,
    productionLeadTimeDays: { min: 2, max: 3 },
    categorySlugs: ["ev-ve-dekorasyon"],
    collectionSlugs: ["yeni-urunler", "sana-ozel"],
    media: [
      {
        id: "demo-media-tidal-1",
        type: "image",
        url: "/demo/products/tidal-saksi.svg",
        alt: "Tidal saksı demo görseli",
        position: 1,
        role: "primary",
        isolated: true,
      },
    ],
    variants: makeVariants("tidal", [
      ["Adaçayı", "#7C8A78"],
      ["Kil", "#A75C42"],
      ["Kemik", "#DED7C8"],
    ]),
    badges: ["new"],
    featured: true,
    seoTitle: `Tidal Modüler Saksı | ${siteConfig.name}`,
    seoDescription: "İç hazneli, modüler ve çağdaş Tidal masaüstü saksısı.",
    publishedAt: "2026-08-08T09:00:00.000Z",
    isDemo: true,
  },
  {
    id: "demo-product-sculpture-01",
    slug: "mono-bust-demo",
    name: "Mono Büst — Demo",
    shortDescription: "Dijital yüzey araştırmasından doğan sınırlı seri obje.",
    description:
      "Mono, düşük poligonlu dijital bir eskizi mat yüzeyli fiziksel bir objeye dönüştürür. Numaralı sınırlı üretim sunumu demo amaçlıdır; gerçek stok değildir.",
    status: "active",
    kind: "made_to_order",
    priceMinor: 124900,
    compareAtPriceMinor: null,
    currency: "TRY",
    sku: "DEMO-MNO-01",
    inventoryQuantity: 6,
    productionLeadTimeDays: { min: 4, max: 6 },
    categorySlugs: ["biblo-ve-heykel"],
    collectionSlugs: ["sinirli-uretim"],
    media: [
      {
        id: "demo-media-mono-1",
        type: "image",
        url: "/demo/products/mono-bust.svg",
        alt: "Mono büst demo ürün görseli",
        position: 1,
        role: "primary",
        isolated: true,
      },
    ],
    variants: makeVariants(
      "mono",
      [
        ["Mermer", "#D9D6CE"],
        ["Kömür", "#282B2E"],
      ],
      6,
    ),
    badges: ["limited"],
    featured: true,
    seoTitle: `Mono Sınırlı Seri Büst | ${siteConfig.name}`,
    seoDescription: "Düşük poligonlu dijital estetiğe sahip Mono dekoratif büst.",
    publishedAt: "2026-05-20T09:00:00.000Z",
    isDemo: true,
  },
  {
    id: "demo-product-desk-01",
    slug: "dock-masaustu-duzenleyici-demo",
    name: "Dock Masaüstü Düzenleyici — Demo",
    shortDescription: "Kalem, telefon ve küçük ekipmanlar için modüler sistem.",
    description:
      "Dock, ihtiyaç değiştikçe eklenebilen modüllerle masaüstündeki küçük ekipmanları tek hizada toplar. Demo katalog kaydıdır.",
    status: "active",
    kind: "ready_stock",
    priceMinor: 74900,
    compareAtPriceMinor: 84900,
    currency: "TRY",
    sku: "DEMO-DCK-01",
    inventoryQuantity: 14,
    productionLeadTimeDays: { min: 1, max: 3 },
    categorySlugs: ["masaustu-aksesuarlari", "fonksiyonel-parcalar"],
    collectionSlugs: ["sana-ozel"],
    media: [
      {
        id: "demo-media-dock-1",
        type: "image",
        url: "/demo/products/dock-organizer.svg",
        alt: "Dock masaüstü düzenleyici demo görseli",
        position: 1,
        role: "primary",
        isolated: true,
      },
    ],
    variants: makeVariants("dock", [
      ["Grafit", "#30363C"],
      ["Buz", "#D9E1E5"],
    ]),
    badges: [],
    featured: false,
    seoTitle: `Dock Modüler Masaüstü Düzenleyici | ${siteConfig.name}`,
    seoDescription: "Telefon ve ekipmanlar için modüler Dock düzenleyici.",
    publishedAt: "2026-04-14T09:00:00.000Z",
    isDemo: true,
  },
  {
    id: "demo-product-cable-01",
    slug: "loop-kablo-klipsi-6li-demo",
    name: "Loop Kablo Klipsi, 6’lı — Demo",
    shortDescription: "Masa kenarında kabloları erişilebilir tutan esnek klips seti.",
    description:
      "TPU malzemeyle üretilen Loop klipsler farklı kablo çaplarına uyum sağlar. Yapışkan yüzey seçimi kullanım alanına göre yapılır. Demo katalog kaydıdır.",
    status: "active",
    kind: "ready_stock",
    priceMinor: 24900,
    compareAtPriceMinor: null,
    currency: "TRY",
    sku: "DEMO-LOP-06",
    inventoryQuantity: 42,
    productionLeadTimeDays: { min: 1, max: 2 },
    categorySlugs: ["masaustu-aksesuarlari", "fonksiyonel-parcalar"],
    collectionSlugs: ["cok-satanlar"],
    media: [
      {
        id: "demo-media-loop-1",
        type: "image",
        url: "/demo/products/loop-clips.svg",
        alt: "Loop kablo klipsi demo görseli",
        position: 1,
        role: "primary",
        isolated: true,
      },
    ],
    variants: makeVariants("loop", [
      ["Siyah", "#15181A"],
      ["Buz", "#CED8DE"],
      ["Turuncu", "#E56732"],
    ]),
    badges: ["bestseller"],
    featured: false,
    seoTitle: `Loop TPU Kablo Klipsi | ${siteConfig.name}`,
    seoDescription: "Esnek TPU malzemeden altılı masaüstü kablo klipsi.",
    publishedAt: "2026-03-03T09:00:00.000Z",
    isDemo: true,
  },
  {
    id: "demo-product-nameplate-01",
    slug: "type-kisiye-ozel-masa-isimligi-demo",
    name: "Type Masa İsimliği — Demo",
    shortDescription: "İsim ve unvana göre üretilen tipografik masa objesi.",
    description:
      "Type, sipariş sırasında girilen isim ve isteğe bağlı unvanla hazırlanır. Tasarım üretim öncesinde dijital olarak onaylanır. Demo katalog kaydıdır.",
    status: "active",
    kind: "made_to_order",
    priceMinor: 44900,
    compareAtPriceMinor: null,
    currency: "TRY",
    sku: "DEMO-TYP-01",
    inventoryQuantity: 99,
    productionLeadTimeDays: { min: 2, max: 4 },
    categorySlugs: ["kisiye-ozel-urunler", "kurumsal-promosyon"],
    collectionSlugs: ["yeni-urunler", "sana-ozel"],
    media: [
      {
        id: "demo-media-type-1",
        type: "image",
        url: "/demo/products/type-nameplate.svg",
        alt: "Type masa isimliği demo görseli",
        position: 1,
        role: "primary",
        isolated: true,
      },
    ],
    variants: makeVariants("type", [
      ["Siyah / Beyaz", "#171A1D"],
      ["Lacivert / Buz", "#17314A"],
      ["Turuncu / Krem", "#D96631"],
    ]),
    badges: ["new"],
    featured: true,
    seoTitle: `Kişiye Özel Type Masa İsimliği | ${siteConfig.name}`,
    seoDescription: "İsim ve unvanla kişiselleştirilen tipografik masa isimliği.",
    publishedAt: "2026-08-10T09:00:00.000Z",
    isDemo: true,
    reviewSummary: { average: 4.9, count: 7, isDemo: true },
  },
];

export const demoCollections: Collection[] = [
  {
    id: "demo-collection-bestsellers",
    slug: "cok-satanlar",
    name: "Çok Satanlar",
    description: "Demo mağazada öne çıkarılan ürünler; gerçek satış verisi değildir.",
    productSlugs: demoProducts
      .filter((product) => product.collectionSlugs.includes("cok-satanlar"))
      .map((product) => product.slug),
    isDemo: true,
  },
  {
    id: "demo-collection-new",
    slug: "yeni-urunler",
    name: "Yeni Ürünler",
    description: "Stüdyonun demo kataloğuna en son eklenen tasarımlar.",
    productSlugs: demoProducts
      .filter((product) => product.collectionSlugs.includes("yeni-urunler"))
      .map((product) => product.slug),
    isDemo: true,
  },
  {
    id: "demo-collection-personal",
    slug: "sana-ozel",
    name: "Sana Özel",
    description: "Renk, ölçü veya isim seçeneği sunan demo ürünler.",
    productSlugs: demoProducts
      .filter((product) => product.collectionSlugs.includes("sana-ozel"))
      .map((product) => product.slug),
    isDemo: true,
  },
  {
    id: "demo-collection-limited",
    slug: "sinirli-uretim",
    name: "Sınırlı Üretim",
    description: "Küçük seri üretim yaklaşımını gösteren demo koleksiyon.",
    productSlugs: demoProducts
      .filter((product) => product.collectionSlugs.includes("sinirli-uretim"))
      .map((product) => product.slug),
    isDemo: true,
  },
];

export const demoMaterials: Material[] = [
  {
    id: "demo-material-pla",
    slug: "pla",
    name: "PLA",
    technology: "FDM",
    summary: "Dekoratif ürünlerde net detay ve geniş renk seçeneği.",
    useCases: ["Dekorasyon", "Maket", "Konsept prototip"],
    durability: 3,
    surfaceQuality: 4,
    heatResistance: 2,
    flexibility: 1,
    suitability: "İç mekân",
    colors: [
      { name: "Kemik", hex: "#DED7C8" },
      { name: "Grafit", hex: "#30363C" },
      { name: "Elektrik mavi", hex: "#21D4FD" },
    ],
    isDemo: true,
  },
  {
    id: "demo-material-petg",
    slug: "petg",
    name: "PETG",
    technology: "FDM",
    summary: "Darbe ve neme daha dayanıklı, işlevsel parça seçeneği.",
    useCases: ["Fonksiyonel parça", "Muhafaza", "Atölye ekipmanı"],
    durability: 4,
    surfaceQuality: 3,
    heatResistance: 3,
    flexibility: 2,
    suitability: "İç / dış mekân",
    colors: [
      { name: "Siyah", hex: "#15181A" },
      { name: "Beyaz", hex: "#F0F1EE" },
      { name: "Şeffaf", hex: "#D8E2E5" },
    ],
    isDemo: true,
  },
  {
    id: "demo-material-tpu",
    slug: "tpu",
    name: "TPU",
    technology: "FDM",
    summary: "Esneyen, darbeyi sönümleyen ve kavrama sağlayan parçalar.",
    useCases: ["Koruyucu", "Conta", "Kablo yönetimi"],
    durability: 4,
    surfaceQuality: 3,
    heatResistance: 3,
    flexibility: 5,
    suitability: "Teknik kullanım",
    colors: [
      { name: "Siyah", hex: "#15181A" },
      { name: "Turuncu", hex: "#E56732" },
    ],
    isDemo: true,
  },
  {
    id: "demo-material-asa",
    slug: "asa",
    name: "ASA",
    technology: "FDM",
    summary: "UV ve hava koşullarına dayanım gerektiren dış ortam parçaları.",
    useCases: ["Dış ortam", "Otomotiv aparatı", "Teknik muhafaza"],
    durability: 4,
    surfaceQuality: 3,
    heatResistance: 4,
    flexibility: 2,
    suitability: "İç / dış mekân",
    colors: [
      { name: "Siyah", hex: "#171A1D" },
      { name: "Kırık beyaz", hex: "#E9E7E0" },
    ],
    isDemo: true,
  },
  {
    id: "demo-material-standard-resin",
    slug: "standart-recine",
    name: "Standart Reçine",
    technology: "SLA",
    summary: "Küçük ölçekte yüksek detay ve pürüzsüz yüzey.",
    useCases: ["Figür", "Sunum modeli", "Detay prototipi"],
    durability: 2,
    surfaceQuality: 5,
    heatResistance: 2,
    flexibility: 1,
    suitability: "İç mekân",
    colors: [
      { name: "Gri", hex: "#8A8E91" },
      { name: "Fildişi", hex: "#DDD6C7" },
    ],
    isDemo: true,
  },
  {
    id: "demo-material-tough-resin",
    slug: "dayanikli-recine",
    name: "Tough Reçine",
    technology: "SLA",
    summary: "Detay ile mekanik dayanımı dengeleyen mühendislik reçinesi.",
    useCases: ["Geçme parça", "Küçük muhafaza", "Fonksiyon prototipi"],
    durability: 4,
    surfaceQuality: 5,
    heatResistance: 3,
    flexibility: 2,
    suitability: "Teknik kullanım",
    colors: [{ name: "Teknik gri", hex: "#62686D" }],
    isDemo: true,
  },
];

export const demoAnnouncements: Announcement[] = [
  {
    id: "demo-announcement-shipping",
    message: "2.000 TL üzeri ücretsiz kargo",
    href: "/magaza",
    isActive: true,
    position: 1,
  },
  {
    id: "demo-announcement-ankara",
    message: "Ankara’dan Türkiye’nin her yerine üretim",
    isActive: true,
    position: 2,
  },
  {
    id: "demo-announcement-bulk",
    message: "Toplu üretim için özel fiyat",
    href: "/kurumsal-teklif",
    isActive: true,
    position: 3,
  },
];

export const demoCatalogSnapshot: CatalogSnapshot = {
  products: demoProducts,
  categories: demoCategories,
  collections: demoCollections,
  materials: demoMaterials,
  announcements: demoAnnouncements,
  updatedAt: "2026-08-17T00:00:00.000Z",
};
