-- Baskı Çiftliği production persistence: extend existing catalog/manufacturing
-- schema for quote revocation, shipping policy versioning, pricing calibration,
-- order-linked quotes, atomic job claim, private manufacturing storage, and RLS.
-- Additive only. Does not reset data or replace catalog/quote systems.

-- ---------------------------------------------------------------------------
-- Profile role audit
-- ---------------------------------------------------------------------------

create table if not exists public.profile_role_audit (
  id bigint generated by default as identity primary key,
  target_user_id uuid not null references public.profiles(id) on delete cascade,
  actor_id uuid references public.profiles(id) on delete set null,
  previous_role public.app_role,
  new_role public.app_role not null,
  previous_is_active boolean,
  new_is_active boolean not null,
  reason text,
  created_at timestamptz not null default now()
);

create index if not exists profile_role_audit_target_idx
  on public.profile_role_audit (target_user_id, created_at desc);

alter table public.profile_role_audit enable row level security;

drop policy if exists profile_role_audit_admin_read on public.profile_role_audit;
create policy profile_role_audit_admin_read
on public.profile_role_audit for select to authenticated
using ((select public.is_admin()));

drop policy if exists profile_role_audit_service on public.profile_role_audit;
create policy profile_role_audit_service
on public.profile_role_audit for all to service_role
using (true) with check (true);

grant select on table public.profile_role_audit to authenticated;
grant all privileges on table public.profile_role_audit to service_role;

create or replace function public.admin_set_profile_access(
  target_user_id uuid,
  new_role public.app_role,
  new_is_active boolean
)
returns public.profiles
language plpgsql
security definer
set search_path = ''
as $$
declare
  changed_profile public.profiles;
  previous public.profiles;
begin
  if not public.is_admin() then
    raise exception 'administrator privileges required'
      using errcode = '42501';
  end if;

  select * into previous from public.profiles where id = target_user_id;
  if previous.id is null then
    raise exception 'profile not found'
      using errcode = 'P0002';
  end if;

  update public.profiles
  set role = new_role,
      is_active = new_is_active
  where id = target_user_id
  returning * into changed_profile;

  insert into public.profile_role_audit (
    target_user_id, actor_id, previous_role, new_role,
    previous_is_active, new_is_active, reason
  ) values (
    target_user_id,
    auth.uid(),
    previous.role,
    new_role,
    previous.is_active,
    new_is_active,
    'admin_set_profile_access'
  );

  return changed_profile;
end;
$$;

-- ---------------------------------------------------------------------------
-- Commerce shipping policy (versioned source of truth)
-- ---------------------------------------------------------------------------

create table if not exists public.commerce_shipping_policies (
  version integer primary key check (version > 0),
  currency text not null default 'TRY' check (currency ~ '^[A-Z]{3}$'),
  standard_shipping_minor bigint not null check (standard_shipping_minor >= 0),
  free_shipping_threshold_minor bigint not null
    check (free_shipping_threshold_minor >= 0),
  activated_at timestamptz,
  activated_by uuid references public.profiles(id) on delete set null,
  notes text,
  created_at timestamptz not null default now()
);

insert into public.commerce_shipping_policies (
  version, currency, standard_shipping_minor, free_shipping_threshold_minor,
  activated_at, notes
)
values (
  1, 'TRY', 8990, 150000, now(),
  'Owner-approved launch shipping policy'
)
on conflict (version) do nothing;

alter table public.commerce_shipping_policies enable row level security;

drop policy if exists shipping_policies_public_read on public.commerce_shipping_policies;
create policy shipping_policies_public_read
on public.commerce_shipping_policies for select to anon, authenticated
using (activated_at is not null);

drop policy if exists shipping_policies_admin_write on public.commerce_shipping_policies;
create policy shipping_policies_admin_write
on public.commerce_shipping_policies for all to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists shipping_policies_service on public.commerce_shipping_policies;
create policy shipping_policies_service
on public.commerce_shipping_policies for all to service_role
using (true) with check (true);

grant select on table public.commerce_shipping_policies to anon, authenticated;
grant all privileges on table public.commerce_shipping_policies to service_role;

alter table public.carts
  add column if not exists shipping_policy_version integer
    references public.commerce_shipping_policies(version) on delete restrict;

alter table public.orders
  add column if not exists shipping_policy_version integer
    references public.commerce_shipping_policies(version) on delete restrict;

alter table public.order_items
  add column if not exists manufacturing_quote_id uuid
    references public.manufacturing_quotes(id) on delete restrict;

create index if not exists order_items_manufacturing_quote_idx
  on public.order_items (manufacturing_quote_id)
  where manufacturing_quote_id is not null;

-- ---------------------------------------------------------------------------
-- Manufacturing: pricing calibration, revocations, integration, events grants
-- ---------------------------------------------------------------------------

alter table public.pricing_configs
  add column if not exists calibration jsonb
    check (calibration is null or jsonb_typeof(calibration) = 'object');

create table if not exists public.pricing_activation_audit (
  id uuid primary key default extensions.gen_random_uuid(),
  at timestamptz not null default now(),
  activated_by uuid references public.profiles(id) on delete set null,
  previous_version integer,
  previous_checksum text,
  new_version integer not null,
  new_checksum text not null,
  formula_id text not null,
  backup_file text,
  verification_passed boolean not null default false,
  cube_gross_minor bigint not null check (cube_gross_minor >= 0)
);

create index if not exists pricing_activation_audit_at_idx
  on public.pricing_activation_audit (at desc);

alter table public.pricing_activation_audit enable row level security;

drop policy if exists pricing_activation_audit_owner_read on public.pricing_activation_audit;
create policy pricing_activation_audit_owner_read
on public.pricing_activation_audit for select to authenticated
using (
  exists (
    select 1 from public.profiles
    where id = auth.uid()
      and role in ('owner'::public.app_role, 'admin'::public.app_role)
      and is_active
  )
);

drop policy if exists pricing_activation_audit_service on public.pricing_activation_audit;
create policy pricing_activation_audit_service
on public.pricing_activation_audit for all to service_role
using (true) with check (true);

grant select on table public.pricing_activation_audit to authenticated;
grant all privileges on table public.pricing_activation_audit to service_role;

create table if not exists public.quote_revocations (
  id uuid primary key default extensions.gen_random_uuid(),
  quote_id uuid not null references public.manufacturing_quotes(id) on delete restrict,
  reason text not null check (char_length(reason) between 3 and 500),
  revoked_by uuid not null references public.profiles(id) on delete restrict,
  revoked_at timestamptz not null default now(),
  unique (quote_id)
);

create index if not exists quote_revocations_revoked_at_idx
  on public.quote_revocations (revoked_at desc);

alter table public.quote_revocations enable row level security;

drop policy if exists quote_revocations_owner_read on public.quote_revocations;
create policy quote_revocations_owner_read
on public.quote_revocations for select to authenticated
using (
  exists (
    select 1 from public.profiles
    where id = auth.uid()
      and role in ('owner'::public.app_role, 'admin'::public.app_role)
      and is_active
  )
);

drop policy if exists quote_revocations_service on public.quote_revocations;
create policy quote_revocations_service
on public.quote_revocations for all to service_role
using (true) with check (true);

grant select on table public.quote_revocations to authenticated;
grant all privileges on table public.quote_revocations to service_role;

create or replace function public.quote_has_linked_order(target_quote_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.order_items
    where manufacturing_quote_id = target_quote_id
  );
$$;

revoke all on function public.quote_has_linked_order(uuid) from public;
grant execute on function public.quote_has_linked_order(uuid)
  to authenticated, service_role;

create or replace function public.revoke_manufacturing_quote(
  target_quote_id uuid,
  revoke_reason text,
  actor_user_id uuid default null
)
returns public.quote_revocations
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor_id uuid;
  actor_role public.app_role;
  record public.quote_revocations;
begin
  actor_id := coalesce(auth.uid(), actor_user_id);
  if actor_id is null then
    raise exception 'actor required'
      using errcode = '42501';
  end if;

  select role into actor_role
  from public.profiles
  where id = actor_id and is_active;

  if actor_role is distinct from 'owner'::public.app_role then
    raise exception 'owner privileges required'
      using errcode = '42501';
  end if;

  if auth.uid() is not null and auth.uid() is distinct from actor_id then
    raise exception 'actor mismatch'
      using errcode = '42501';
  end if;

  if not exists (
    select 1 from public.manufacturing_quotes where id = target_quote_id
  ) then
    raise exception 'quote not found'
      using errcode = 'P0002';
  end if;

  if exists (
    select 1 from public.quote_revocations where quote_id = target_quote_id
  ) then
    raise exception 'quote already revoked'
      using errcode = '23505';
  end if;

  if public.quote_has_linked_order(target_quote_id) then
    raise exception 'order-linked quotes cannot be revoked'
      using errcode = '23514';
  end if;

  insert into public.quote_revocations (quote_id, reason, revoked_by)
  values (target_quote_id, btrim(revoke_reason), actor_id)
  returning * into record;

  return record;
end;
$$;

revoke all on function public.revoke_manufacturing_quote(uuid, text, uuid) from public;
grant execute on function public.revoke_manufacturing_quote(uuid, text, uuid)
  to authenticated, service_role;

create table if not exists public.manufacturing_integration_status (
  id integer primary key default 1 check (id = 1),
  thingiverse_last_success_at timestamptz,
  thingiverse_last_failure_at timestamptz,
  thingiverse_last_error text,
  thingiverse_rate_limited_until timestamptz,
  worker_last_seen_at timestamptz,
  worker_version text,
  prusa_slicer_version text,
  updated_at timestamptz not null default now()
);

insert into public.manufacturing_integration_status (id)
values (1)
on conflict (id) do nothing;

alter table public.manufacturing_integration_status enable row level security;

drop policy if exists manufacturing_integration_staff_read
  on public.manufacturing_integration_status;
create policy manufacturing_integration_staff_read
on public.manufacturing_integration_status for select to authenticated
using ((select public.is_catalog_viewer()));

drop policy if exists manufacturing_integration_service
  on public.manufacturing_integration_status;
create policy manufacturing_integration_service
on public.manufacturing_integration_status for all to service_role
using (true) with check (true);

grant select on table public.manufacturing_integration_status to authenticated;
grant all privileges on table public.manufacturing_integration_status to service_role;

-- ---------------------------------------------------------------------------
-- Atomic worker claim (SKIP LOCKED)
-- ---------------------------------------------------------------------------

create or replace function public.claim_quote_job(
  worker_id text,
  lease_ms integer default 720000
)
returns public.quote_jobs
language plpgsql
security definer
set search_path = ''
as $$
declare
  claimed public.quote_jobs;
  lock_cutoff timestamptz := now() - make_interval(secs => greatest(lease_ms, 1000) / 1000.0);
begin
  if coalesce(auth.role(), '') <> 'service_role' then
    raise exception 'service role required for job claim'
      using errcode = '42501';
  end if;

  -- Recover stale in-flight leases so another worker may reclaim.
  update public.quote_jobs
  set state = 'uploaded'::public.quote_job_state,
      locked_at = null,
      locked_by = null,
      error_code = 'stale_lease',
      error_message = 'Stale worker lease recovered.',
      updated_at = now()
  where locked_at is not null
    and locked_at < lock_cutoff
    and state in (
      'validating'::public.quote_job_state,
      'analyzing'::public.quote_job_state,
      'slicing'::public.quote_job_state
    )
    and quote_id is null
    and completed_at is null;

  with candidate as (
    select id
    from public.quote_jobs
    where quote_id is null
      and completed_at is null
      and attempt_count < max_attempts
      and locked_at is null
      and state in (
        'created'::public.quote_job_state,
        'uploaded'::public.quote_job_state
      )
    order by created_at asc
    for update skip locked
    limit 1
  )
  update public.quote_jobs as job
  set locked_at = now(),
      locked_by = worker_id,
      attempt_count = job.attempt_count + 1,
      state = 'slicing'::public.quote_job_state,
      started_at = coalesce(job.started_at, now()),
      error_code = null,
      error_message = null,
      updated_at = now()
  from candidate
  where job.id = candidate.id
  returning job.* into claimed;

  return claimed;
end;
$$;

revoke all on function public.claim_quote_job(text, integer) from public;
grant execute on function public.claim_quote_job(text, integer) to service_role;

-- ---------------------------------------------------------------------------
-- Manufacturing RLS: customers own rows; staff read; no public anon access
-- ---------------------------------------------------------------------------

drop policy if exists manufacturing_files_owner_read on public.manufacturing_files;
create policy manufacturing_files_owner_read
on public.manufacturing_files for select to authenticated
using (
  owner_user_id = auth.uid()
  or (select public.is_admin())
);

drop policy if exists manufacturing_files_owner_insert on public.manufacturing_files;
create policy manufacturing_files_owner_insert
on public.manufacturing_files for insert to authenticated
with check (
  owner_user_id = auth.uid()
);

drop policy if exists manufacturing_files_service on public.manufacturing_files;
create policy manufacturing_files_service
on public.manufacturing_files for all to service_role
using (true) with check (true);

drop policy if exists quote_jobs_owner_read on public.quote_jobs;
create policy quote_jobs_owner_read
on public.quote_jobs for select to authenticated
using (
  owner_user_id = auth.uid()
  or (select public.is_admin())
);

drop policy if exists quote_jobs_service on public.quote_jobs;
create policy quote_jobs_service
on public.quote_jobs for all to service_role
using (true) with check (true);

drop policy if exists manufacturing_quotes_owner_read on public.manufacturing_quotes;
create policy manufacturing_quotes_owner_read
on public.manufacturing_quotes for select to authenticated
using (
  owner_user_id = auth.uid()
  or (select public.is_admin())
);

-- Internal cost columns remain in the row; application DTOs strip them for
-- public/customer endpoints. Clients cannot update signature/pricing fields.
drop policy if exists manufacturing_quotes_owner_update_blocked
  on public.manufacturing_quotes;
create policy manufacturing_quotes_no_client_write
on public.manufacturing_quotes for insert to authenticated
with check (false);

drop policy if exists manufacturing_quotes_no_client_update
  on public.manufacturing_quotes;
create policy manufacturing_quotes_no_client_update
on public.manufacturing_quotes for update to authenticated
using (false)
with check (false);

drop policy if exists manufacturing_quotes_service on public.manufacturing_quotes;
create policy manufacturing_quotes_service
on public.manufacturing_quotes for all to service_role
using (true) with check (true);

drop policy if exists quote_status_events_owner_read on public.quote_status_events;
create policy quote_status_events_owner_read
on public.quote_status_events for select to authenticated
using (
  exists (
    select 1 from public.quote_jobs j
    where j.id = quote_status_events.job_id
      and (j.owner_user_id = auth.uid() or (select public.is_admin()))
  )
);

drop policy if exists quote_status_events_service on public.quote_status_events;
create policy quote_status_events_service
on public.quote_status_events for all to service_role
using (true) with check (true);

drop policy if exists pricing_configs_staff_read on public.pricing_configs;
create policy pricing_configs_staff_read
on public.pricing_configs for select to authenticated
using (
  exists (
    select 1 from public.profiles
    where id = auth.uid()
      and role in ('owner'::public.app_role, 'admin'::public.app_role)
      and is_active
  )
);

drop policy if exists pricing_configs_service on public.pricing_configs;
create policy pricing_configs_service
on public.pricing_configs for all to service_role
using (true) with check (true);

grant select on table public.manufacturing_files to authenticated;
grant select on table public.quote_jobs to authenticated;
grant select on table public.manufacturing_quotes to authenticated;
grant select on table public.quote_status_events to authenticated;
grant select on table public.pricing_configs to authenticated;
grant select on table public.model_permission_reviews to authenticated;
grant all privileges on table public.manufacturing_files to service_role;
grant all privileges on table public.quote_jobs to service_role;
grant all privileges on table public.manufacturing_quotes to service_role;
grant all privileges on table public.quote_status_events to service_role;
grant all privileges on table public.pricing_configs to service_role;
grant all privileges on table public.model_permission_reviews to service_role;

-- ---------------------------------------------------------------------------
-- Private manufacturing objects bucket (original meshes only)
-- ---------------------------------------------------------------------------

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'manufacturing-objects',
  'manufacturing-objects',
  false,
  104857600,
  array[
    'application/octet-stream',
    'application/sla',
    'model/stl',
    'model/obj',
    'model/3mf',
    'application/vnd.ms-package.3dmanufacturing-3dmodel+xml'
  ]::text[]
)
on conflict (id) do update
set public = false,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists manufacturing_objects_owner_read on storage.objects;
create policy manufacturing_objects_owner_read
on storage.objects for select to authenticated
using (
  bucket_id = 'manufacturing-objects'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

drop policy if exists manufacturing_objects_owner_insert on storage.objects;
create policy manufacturing_objects_owner_insert
on storage.objects for insert to authenticated
with check (
  bucket_id = 'manufacturing-objects'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

drop policy if exists manufacturing_objects_admin_read on storage.objects;
create policy manufacturing_objects_admin_read
on storage.objects for select to authenticated
using (
  bucket_id = 'manufacturing-objects'
  and (select public.is_admin())
);

drop policy if exists manufacturing_objects_service on storage.objects;
create policy manufacturing_objects_service
on storage.objects for all to service_role
using (bucket_id = 'manufacturing-objects')
with check (bucket_id = 'manufacturing-objects');

revoke select (cost_price_minor) on table public.products from anon, authenticated;

comment on column public.products.cost_price_minor is
  'Staff-only product cost. Not granted to anon/authenticated; admin APIs use service role.';

comment on function public.revoke_manufacturing_quote(uuid, text, uuid) is
  'Owner-only quote invalidation; does not rewrite signed quote payloads.';

comment on function public.claim_quote_job(text, integer) is
  'Atomic SKIP LOCKED claim for slicer workers via service-role Next.js boundary.';
comment on table public.commerce_shipping_policies is
  'Versioned cart shipping policy; quote gross excludes shipping.';
